/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro pstupnost",contents:"Obsah npovdy. Pro uzaven tohoto dialogu stisknte klvesu ESC.",legend:[{name:"Obecn",items:[{name:"Panel nstroj editoru",legend:"Stisknte${toolbarFocus} k prochzen panelu nstroj. Pejdte na dal a pedchoz skupiny pomoc TAB a SHIFT-TAB. Pechod na dal a pedchoz tlatko panelu nstroj je pomoc IPKA VPRAVO nebo IPKA VLEVO. Stisknutm mezernku nebo klvesy ENTER tlatko aktivujete."},{name:"Dialogov okno editoru",
legend:"Uvnit dialogovho okna stisknte TAB pro pesunut na dal pole, stisknte SHIFT + TAB pro pesun na pedchoz pole, stisknte ENTER pro odesln dialogu, stisknte ESC pro jeho zruen. Pro dialogov okna, kter maj mnoho karet stisknte ALT + F10 pr oprochzen seznamu karet. Pak se pesute na dal kartu pomoc TAB nebo IPKA VPRAVO. Pro pesun na pedchoz stisknte SHIFT + TAB nebo IPKA VLEVO. Stisknte MEZERNK nebo ENTER pro vybrn strnky karet."},{name:"Kontextov menu editoru",
legend:"Stisknte ${contextMenu} nebo klvesu APPLICATION k oteven kontextovho menu. Pak se pesute na dal monost menu pomoc TAB nebo IPKY DOL. Pesute se na pedchoz monost pomoc  SHIFT+TAB nebo IPKY NAHORU. Stisknte MEZERNK nebo ENTER pro zvolen monosti menu. Podmenu souasn monosti otevete pomoc MEZERNKU nebo ENTER i IPKY DOLEVA. Kontextov menu uzavete stiskem ESC."},{name:"Rmeek seznamu editoru",legend:"Uvnit rmeku seznamu se pesunete na dal poloku menu pomoc TAB nebo IPKA DOL. Na pedchoz poloku se pesunete SHIFT + TAB nebo IPKA NAHORU. Stisknte MEZERNK nebo ENTER pro zvolen monosti seznamu. Stisknte ESC pro uzaven seznamu."},
{name:"Lita cesty prvku v editoru",legend:"Stisknte ${elementsPathFocus} pro prochzen lity cesty prvku. Na dal tlatko prvku se pesunete pomoc TAB nebo IPKA VPRAVO. Na pedchoz poloku se pesunete pomoc SHIFT + TAB nebo IPKA VLEVO. Stisknte MEZERNK nebo ENTER pro vybrn prvku v editoru."}]},{name:"Pkazy",items:[{name:" Pkaz Zpt",legend:"Stisknte ${undo}"},{name:" Pkaz Znovu",legend:"Stisknte ${redo}"},{name:" Pkaz Tun",legend:"Stisknte ${bold}"},{name:" Pkaz Kurzva",
legend:"Stisknte ${italic}"},{name:" Pkaz Podtren",legend:"Stisknte ${underline}"},{name:" Pkaz Odkaz",legend:"Stisknte ${link}"},{name:" Pkaz Skrt panel nstroj",legend:"Stisknte ${toolbarCollapse}"},{name:"Pkaz pro pstup k pedchozmu prostoru zamen",legend:"Stisknte ${accessPreviousSpace} pro pstup k nejblimu nedosaitelnmu prostoru zamen ped stkou, napklad: dva pilehl prvky HR. Pro dosaen vzdlench prostor zamen tuto kombinaci klves opakujte."},{name:"Pkaz pro pstup k dalmu prostoru zamen",
legend:"Stisknte ${accessNextSpace} pro pstup k nejblimu nedosaitelnmu prostoru zamen po stce, napklad: dva pilehl prvky HR. Pro dosaen vzdlench prostor zamen tuto kombinaci klves opakujte."},{name:" Npovda pstupnosti",legend:"Stisknte ${a11yHelp}"}]}]});