/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","eo",{title:"Uzindikoj pri atingeblo",contents:"Helpilenhavo. Por fermi tiun dialogon, premu la ESKAPAN klavon.",legend:[{name:"eneralaoj",items:[{name:"Ilbreto de la redaktilo",legend:"Premu ${toolbarFocus} por atingi la ilbreton. Moviu al la sekva a antaa grupoj de la ilbreto per la klavoj TABA kaj MAJUSKLIGA-TABA. Moviu al la sekva a antaa butonoj de la ilbreto per la klavoj SAGO DEKSTREN kaj SAGO MALDEKSTREN. Premu la SPACETklavon a la ENENklavon por aktivigi la ilbretbutonon."},
{name:"Redaktildialogo",legend:"En dialogo, premu la TABAN klavon por navigi al la sekva dialogkampo, premu la MAJUSKLIGAN + TABAN klavojn por reveni al la antaa kampo, premu la ENENklavon por sendi la dialogon, premu la ESKAPAN klavon por nuligi la dialogon. Por dialogoj kun pluraj retpaoj sub langetoj, premu ALT + F10 por navigi al la langetlisto. Poste moviu al la sekva langeto per la klavo TABA a SAGO DEKSTREN. Moviu al la antaa langeto per la klavoj MAJUSKLIGA + TABA a  SAGO MALDEKSTREN. Premu la SPACETklavon a la ENENklavon por selekti la langetretpaon."},
{name:"Kunteksta menuo de la redaktilo",legend:"Premu ${contextMenu} a entajpu la KLAVKOMBINAON por malfermi la kuntekstan menuon. Poste moviu al la sekva opcio de la menuo per la klavoj TABA a SAGO SUBEN. Moviu al la antaa opcio per la klavoj MAJUSKLGA + TABA a SAGO SUPREN. Premu la SPACETklavon a ENENklavon por selekti la menuopcion. Malfermu la submenuon de la kuranta opcio per la SPACETklavo a la ENENklavo a la SAGO DEKSTREN. Revenu al la elemento de la patra menuo per la klavoj ESKAPA a SAGO MALDEKSTREN. Fermu la kuntekstan menuon per la ESKAPA klavo."},
{name:"Fallisto de la redaktilo",legend:"En fallisto, moviu al la sekva listelemento per la klavoj TABA a SAGO SUBEN. Moviu al la antaa listelemento per la klavoj MAJUSKLIGA + TABA a SAGO SUPREN. Premu la SPACETklavon a ENENklavon por selekti la opcion en la listo. Premu la ESKAPAN klavon por fermi la falmenuon."},{name:"Breto indikanta la vojon al la redaktilelementoj",legend:"Premu ${elementsPathFocus} por navigi al la breto indikanta la vojon al la redaktilelementoj. Moviu al la butono de la sekva elemento per la klavoj TABA a SAGO DEKSTREN. Moviu al la butono de la antaa elemento per la klavoj MAJUSKLIGA + TABA a SAGO MALDEKSTREN. Premu la SPACETklavon a ENENklavon por selekti la elementon en la redaktilo."}]},
{name:"Komandoj",items:[{name:"Komando malfari",legend:"Premu ${undo}"},{name:"Komando refari",legend:"Premu ${redo}"},{name:"Komando grasa",legend:"Premu ${bold}"},{name:"Komando kursiva",legend:"Premu ${italic}"},{name:"Komando substreki",legend:"Premu ${underline}"},{name:"Komando ligilo",legend:"Premu ${link}"},{name:"Komando faldi la ilbreton",legend:"Premu ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Helpilo pri atingeblo",legend:"Premu ${a11yHelp}"}]}]});