/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sisllt. Sulkeaksesi tmn dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin tykalupalkki",legend:"Paina ${toolbarFocus} siirtyksesi tykalupalkkiin. Siirry seuraavaan ja edelliseen tykalupalkin ryhmn TAB ja SHIFT-TAB nppimill. Siirry seuraavaan ja edelliseen tykalupainikkeeseen kyttmll NUOLI OIKEALLE tai NUOLI VASEMMALLE nppimill. Paina VLILYNTI tai ENTER nppint aktivoidaksesi tykalupainikkeen."},
{name:"Editorin dialogi",legend:"Dialogin sisll, painamalla TAB siirryt seuraavaan dialogin kenttn, painamalla SHIFT+TAB siirryt aiempaan kenttn, painamalla ENTER lhett dialogin, painamalla ESC peruutat dialogin. Dialogeille joissa on useita vlilehti, paina ALT+F10 siirtyksesi vlillehtilistaan. Siirtyksesi seuraavaan vlilehteen paina TAB tai NUOLI OIKEALLE. Siirry edelliseen vlilehteen painamalla SHIFT+TAB tai nuoli vasemmalle. Paina VLILYNTI tai ENTER valitaksesi vlilehden."},{name:"Editorin oheisvalikko",
legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS nppimill. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YLS nppimill. Paina VLILYNTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina VLILYNTI tai ENTER tai NUOLI OIKEALLE painiketta. Siirtyksesi takaisin valikon ylemmlle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},{name:"Editorin listalaatikko",
legend:"Listalaatikon sisll siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YLS painikkeilla. Paina VLILYNTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirtyksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina VLILYNTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"Pienenn tykalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}]});