/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr-ca",{title:"Instructions d'accessibilit",contents:"Contenu de l'aide.  Pour fermer cette fentre, appuyez sur ESC.",legend:[{name:"Gnral",items:[{name:"Barre d'outil de l'diteur",legend:"Appuyer sur ${toolbarFocus} pour accder  la barre d'outils. Se dplacer vers les groupes suivant ou prcdent de la barre d'outil avec les touches TAB et SHIFT-TAB. Se dplacer vers les boutons suivant ou prcdent de la barre d'outils avec les touches FLECHE DROITE et FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour activer le bouton de barre d'outils."},
{name:"Dialogue de l'diteur",legend:"A l'intrieur d'un dialogue, appuyer sur la touche TAB pour naviguer jusqu'au champ de dalogue suivant, appuyez sur les touches SHIFT + TAB pour revenir au champ prcdent, appuyez sur la touche ENTRER pour soumettre le dialogue, appuyer sur la touche ESC pour annuler le dialogue. Pour les dialogues avec plusieurs pages d'onglets, appuyer sur ALT + F10 pour naviguer jusqu' la liste des onglets. Puis se dplacer vers l'onglet suivant avec la touche TAB ou FLECHE DROITE. Se dplacer vers l'onglet prcdent avec les touches SHIFT + TAB ou FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour slectionner la page de l'onglet."},
{name:"Menu contextuel de l'diteur",legend:"Appuyer sur ${contextMenu} ou entrer le RACCOURCI CLAVIER pour ouvrir le menu contextuel. Puis se dplacer vers l'option suivante du menu avec les touches TAB ou FLECHE BAS. Se dplacer vers l'option prcdente avec les touches SHIFT+TAB ou FLECHE HAUT. appuyer sur la BARRE D'ESPACE ou la touche ENTREE pour slectionner l'option du menu. Oovrir le sous-menu de l'option courante avec la BARRE D'ESPACE ou les touches ENTREE ou FLECHE DROITE. Revenir  l'lment de menu parent avec les touches ESC ou FLECHE GAUCHE. Fermer le menu contextuel avec ESC."},
{name:"Menu droulant de l'diteur",legend:"A l'intrieur d'une liste en menu droulant, se dplacer vers l'lment suivant de la liste avec les touches TAB ou FLECHE BAS. Se dplacer vers l'lment prcdent de la liste avec les touches SHIFT + TAB ou FLECHE HAUT. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour slectionner l'option dans la liste. Appuyer sur ESC pour fermer le menu droulant."},{name:"Barre d'emplacement des lments de l'diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre d'emplacement des lments de lditeur. Se dplacer vers le bouton d'lment suivant avec les touches TAB ou FLECHE DROITE. Se dplacer vers le bouton d'lment prcdent avec les touches SHIFT+TAB ou FLECHE GAUCHE. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour slectionner l'lment dans l'diteur."}]},
{name:"Commandes",items:[{name:"Annuler",legend:"Appuyer sur ${undo}"},{name:"Refaire",legend:"Appuyer sur ${redo}"},{name:"Gras",legend:"Appuyer sur ${bold}"},{name:"Italique",legend:"Appuyer sur ${italic}"},{name:"Soulign",legend:"Appuyer sur ${underline}"},{name:"Lien",legend:"Appuyer sur ${link}"},{name:"Enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Accder  l'objet de focus prcdent",legend:"Appuyer ${accessPreviousSpace} pour accder au prochain espace disponible avant le curseur, par exemple: deux lments HR adjacents.  Rpter la combinaison pour joindre les lments d'espaces distantes."},
{name:"Accder au prochain objet de focus",legend:"Appuyer ${accessNextSpace} pour accder au prochain espace disponible aprs le curseur, par exemple: deux lments HR adjacents.  Rpter la combinaison pour joindre les lments d'espaces distantes."},{name:"Aide d'accessibilit",legend:"Appuyer sur ${a11yHelp}"}]}]});