/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilit",contents:"Contenu de l'aide. Pour fermer ce dialogue, appuyez sur la touche Ech (Echappement).",legend:[{name:"Gnral",items:[{name:"Barre d'outils de l'diteur",legend:"Appuyer sur ${toolbarFocus} pour accder  la barre d'outils. Se dplacer vers les groupes suivant ou prcdent de la barre d'outil avec les touches TAB et SHIFT-TAB. Se dplacer vers les boutons suivant ou prcdent de la barre d'outils avec les touches FLECHE DROITE et FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour activer le bouton de barre d'outils."},
{name:"Dialogue de l'diteur",legend:"A l'intrieur d'un dialogue, appuyer sur la touche TAB pour naviguer jusqu'au champ de dalogue suivant, appuyez sur les touches SHIFT + TAB pour revenir au champ prcdent, appuyez sur la touche ENTRER pour soumettre le dialogue, appuyer sur la touche ESC pour annuler le dialogue. Pour les dialogues avec plusieurs pages d'onglets, appuyer sur ALT + F10 pour naviguer jusqu' la liste des onglets. Puis se dplacer vers l'onglet suivant avec la touche TAB ou FLECHE DROITE. Se dplacer vers l'onglet prcdent avec les touches SHIFT + TAB ou FLECHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTRER pour slectionner la page de l'onglet."},
{name:"Menu contextuel de l'diteur",legend:"Appuyer sur ${contextMenu} ou entrer le RACCOURCI CLAVIER pour ouvrir le menu contextuel. Puis se dplacer vers l'option suivante du menu avec les touches TAB ou FLECHE BAS. Se dplacer vers l'option prcdente avec les touches  SHIFT+TAB ou FLECHE HAUT. appuyer sur la BARRE D'ESPACE ou la touche ENTREE pour slectionner l'option du menu. Oovrir le sous-menu de l'option courante avec la BARRE D'ESPACE ou les touches ENTREE ou FLECHE DROITE. Revenir  l'lment de menu parent avec les touches Ech ou FLECHE GAUCHE. Fermer le menu contextuel avec Ech."},
{name:"Zone de liste de l'diteur",legend:"Dans la liste en menu droulant, se dplacer vers l'lment suivant de la liste avec les touches TAB ou FLECHE BAS. Se dplacer vers l'lment prcdent de la liste avec les touches MAJ + TAB ou FLECHE HAUT. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour slectionner l'option dans la liste. Appuyer sur ESC pour fermer le menu droulant."},{name:"Barre d'emplacement des lments de l'diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre d'emplacement des lments de l'diteur. Se dplacer vers le bouton d'lment suivant avec les touches TAB ou FLECHE DROITE. Se dplacer vers le bouton d'lment prcdent avec les touches MAJ+TAB ou FLECHE GAUCHE. Appuyer sur la BARRE D'ESPACE ou sur ENTREE pour slectionner l'lment dans l'diteur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Refaire la commande",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande soulign",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Accder  la prcdente commande d'espace de mise au point",
legend:"Appuyez sur ${accessPreviousSpace} pour accder  l'espace hors d'atteinte le plus proche avant le caret, par exemple: deux lments HR adjacents. Rptez la combinaison de touches pour atteindre les espaces de mise au point distants."},{name:"Accs  la prochaine commande de l'espace de mise au point",legend:"Appuyez sur ${accessNextSpace} pour accder au plus proche espace de mise au point hors d'atteinte aprs le caret, par exemple: deux lments HR adjacents. rptez la combinaison de touches pour atteindre les espace de mise au point distants."},
{name:" Aide Accessibilit",legend:"Appuyer sur ${a11yHelp}"}]}]});