/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","gl",{title:"Instrucins de accesibilidade",contents:"Axuda. Para pechar este dilogo prema ESC.",legend:[{name:"Xeral",items:[{name:"Barra de ferramentas do editor",legend:"Prema ${toolbarFocus} para navegar pola barra de ferramentas. Para moverse polos distintos grupos de ferramentas use as teclas TAB e MAIS+TAB. Para moverse polas distintas ferramentas use FRECHA DEREITA ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para activar o botn da barra de ferramentas."},
{name:"Editor de dilogo",legend:"Dentro dun cadro de dilogo, prema a tecla TAB para desprazarse ao campo seguinte do cadro de dilogo, prema MAIS + TAB para desprazarse ao campo anterior, prema INTRO para presentar o cadro de dilogo, prema a tecla ESC para cancelar o dilogo. Para os dilogos que teen varias pxinas, prema ALT + F10 para navegar  lapela da lista. Despois pasar  seguinte lapela con TAB ou FRECHA DEREITA. Para ir  lapela anterior con SHIFT + TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar a lapela da pxina."},
{name:"Editor do men contextual",legend:"Prema ${contextMenu} ou a TECLA MEN para abrir o men contextual. A seguir mvase  seguinte opcin do men con TAB ou FRECHA ABAIXO. Mvase  opcin anterior con MAIS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para seleccionar a opcin do men. Abra o submen da opcin actual con ESPAZO ou INTRO ou FRECHA DEREITA. Regrese ao elemento principal do men con ESC ou FRECHA ESQUERDA. Peche o men contextual con ESC."},{name:"Lista do editor",legend:"Dentro dunha lista, mvase ao seguinte elemento da lista con TAB ou FRECHA ABAIXO. Mvase ao elemento anterior da lista con MAIS + TAB ou FRECHA ARRIBA. Prema ESPAZO ou INTRO para escoller a opcin da lista. Prema ESC para pechar a lista."},
{name:"Barra da ruta ao elemento no editor",legend:"Prema ${elementsPathFocus} para navegar ata os elementos da barra de ruta. Mvase ao seguinte elemento botn con TAB ou FRECHA DEREITA. Mvase ao botn anterior con MAIS + TAB ou FRECHA ESQUERDA. Prema ESPAZO ou INTRO para seleccionar o elemento no editor."}]},{name:"Ordes",items:[{name:"Orde «desfacer»",legend:"Prema ${undo}"},{name:"Orde «refacer»",legend:"Prema ${redo}"},{name:"Orde «negra»",legend:"Prema ${bold}"},{name:"Orde «cursiva»",legend:"Prema ${italic}"},
{name:"Orde «subliar»",legend:"Prema ${underline}"},{name:"Orde «ligazn»",legend:"Prema ${link}"},{name:"Orde «contraer a barra de ferramentas»",legend:"Prema ${toolbarCollapse}"},{name:"Orde «acceder ao anterior espazo en foco»",legend:"Prema ${accessPreviousSpace} para acceder ao espazo mis prximo de foco inalcanzbel anterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinacin de teclas para chegar a espazos de foco distantes."},{name:"Orde «acceder ao seguinte espazo en foco»",
legend:"Prema ${accessNextSpace} para acceder ao espazo mis prximo de foco inalcanzbel posterior ao cursor, por exemplo: dous elementos HR adxacentes. Repita a combinacin de teclas para chegar a espazos de foco distantes."},{name:"Axuda da accesibilidade",legend:"Prema ${a11yHelp}"}]}]});