/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"Kisegt utastsok",contents:"Sg tartalmak. A prbeszdablak bezrshoz nyomjon ESC-et.",legend:[{name:"ltalnos",items:[{name:"Szerkeszt Eszkztr",legend:"Nyomjon ${toolbarFocus} hogy kijellje az eszkztrat. A kvetkez s elz eszkztr csoporthoz a TAB s SHIFT TAB-al juthat el. A kvetkez s elz eszkztr gombhoz a BAL NYL vagy JOBB NYL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktivlja az eszkztr gombot."},{name:"Szerkesz prbeszd ablak",
legend:"Prbeszdablakban nyomjon TAB-ot a kvetkez prbeszdmezhz ugrshoz, nyomjon SHIFT + TAB-ot az elz mezhz ugrshoz, nyomjon ENTER-t a prbeszdablak elfogadshoz, nyomjon ESC-et a prbeszdablak elvetshez. Azokhoz a prbeszdablakokhoz, amik tbb flet tartalmaznak, nyomjon ALT + F10-et hogy a flekre ugorjon. Ezutn a TAB-al vagy a JOBB NYLLAL a kvetkez flre ugorhat. Az elz flre ugrshoz hasznlja a SHIFT + TAB-ot vagy a BAL NYILAT. Nyomjon SPACE-t vagy ENTER-t hogy kijellje a flet."},
{name:"Szerkeszt helyi men",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZS BILLENTYT a helyi men megnyitshoz. Ezutn a kvetkez menpontra lphet a TAB vagy LEFEL NYLLAL. Az elz opcit a SHIFT+TAB vagy FELFEL NYLLAL rheti el. Nyomjon SPACE-t vagy ENTER-t a menpont kivlasztshoz. A jelenlegi menpont almenjnek megnyitshoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A fmenhz val visszatrshez nyomjon ESC-et vagy BAL NYILAT. A helyi men bezrsa az ESC billentyvel lehetsges."},
{name:"Szerkeszt lista",legend:"A listn bell a kvetkez elemre a TAB vagy LEFEL NYLLAL mozoghat. Az elz elem kivlasztshoz nyomjon SHIFT+TAB-ot vagy FELFEL NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kivlasztshoz. Az ESC billenty megnyomsval bezrhatja a listt."},{name:"Szerkeszt elem utak sv",legend:"Nyomj ${elementsPathFocus} hogy kijelld a elemek t svjt. A kvetkez elem gombhoz a TAB-al vagy a JOBB NYLLAL juthatsz el. Az elz gombhoz a SHIFT+TAB vagy BAL NYLLAL mehetsz. A SPACE vagy ENTER billentyvel kivlaszthatod az elemet a szerkesztben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonsa",legend:"Nyomj ${undo}"},{name:"Parancs megismtlse",legend:"Nyomjon ${redo}"},{name:"Flkvr parancs",legend:"Nyomjon ${bold}"},{name:"Dlt parancs",legend:"Nyomjon ${italic}"},{name:"Alhzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"Szerkesztsv sszecsuksa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"Hozzfrs az elz fkusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzfrj a legkzelebbi elrhetetlen fkusz helyhez a hinyjel eltt, pldul: kt szomszdos HR elemhez. Ismteld meg a billentykombincit hogy megtalld a tvolabbi fkusz helyeket."},
{name:"Hozzfrs a kvetkez fkusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzfrj a legkzelebbi elrhetetlen fkusz helyhez a hinyjel utn, pldul: kt szomszdos HR elemhez. Ismteld meg a billentykombincit hogy megtalld a tvolabbi fkusz helyeket."},{name:"Kisegt sg",legend:"Nyomjon ${a11yHelp}"}]}]});