/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"Pieejambas instrukcija",contents:"Paldzbas saturs. Lai aizvrtu ciet o dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora rkjosla",legend:"Nospiediet ${toolbarFocus} lai prvietotos uz rkjoslu. Lai prvietotos uz nkoo vai iepriekjo rkjoslas grupu izmantojiet pogu TAB un SHIFT+TAB.  Lai prvietotos uz nkoo vai iepriekjo rkjoslas pogu izmantojiet Kreiso vai Labo bultiu. Nospiediet Atstarpi vai ENTER lai aktiviztu rkjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Dialoga log nospiediet pogu TAB lai prvietotos uz nkoo dialoga loga lauku, nospiediet SHIFT+TAB lai atgrieztos iepriekj lauk, nospiediet ENTER lai apstiprintu dialoga datus, nospiediet ESC lai aizvrtu o dialogu. Dialogam kuram ir vairkas cilnes, nospiediet ALT+F10 lai prvietotos uz nepiecieamo cilni.  Lai prvietotos uz nkoo cilni izmantojiet pogu TAB vai Labo bultiu. Lai prvietotos uz iepriekjo cilni nospiediet SHIFT+TAB vai kreiso bultiu. Nospiediet SPACE vai ENTER lai izvltos lapas cilni."},
{name:"Redaktora satura izvle",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvrtu satura izvlni. Lai prvietotos uz nkoo izvlnes opciju izmantojiet pogu TAB vai pogu Bultiu uz leju. Lai prvietotos uz iepriekjo opciju izmantojiet  SHIFT+TAB vai pogu Bultia uz augu. Nospiediet SPACE vai ENTER lai izveltos izvlnes opciju. Atveriet tekoaj opcija apakizvlni ar SAPCE vai ENTER ka ari to var izdart ar Labo bultiu. Lai atgrieztos atpaka uz sakuma izvlni nospiediet ESC vai Kreiso bultiu. Lai aizvrtu ciet izvlnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta lauk, lai prvietotos uz nkoo saraksta elementu nospiediet TAB vai pogu Bultia uz leju. Lai prvietotos uz iepriekjo saraksta elementu nospiediet SHIFT+TAB vai pogu Bultia uz augu. Nospiediet SPACE vai ENTER lai izvltos saraksta opcijas. Nospiediet ESC lai aizvrtu saraksta lauku. "},{name:"Redaktora elementa cea josla",legend:"Nospiediet ${elementsPathFocus} lai prvietotos uz  elementa cea joslu. Lai prvietotos uz nkoo elementa pogu izmantojiet TAB vai Labo bultiu. Lai prvietotos uz iepriekjo elementa pogu  izmantojiet SHIFT + TAB vai Kreiso bultiu. Nospiediet SPACE vai ENTER lai izvltos elementu redaktor."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darbbu",legend:"Nospiediet ${undo}"},{name:"Komanda atkrtot darbbu",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"Kursva komanda",legend:"Nospiediet ${italic}"},{name:"Apaksvtras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"Rkjoslas aizvranas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"Piekt iepriekjai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai piektu tuvkajai nepieejamajai fokusa vietai pirms kursora. Piemram: diviem blakus esoiem lnijas HR elementiem. Atkrtojiet taustiu kombinciju lai piektu pie tlkm vietm."},{name:"Piekt nko fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai piektu tuvkajai nepieejamajai fokusa vietai pc kursora. Piemram: diviem blakus esoiem lnijas HR elementiem. Atkrtojiet taustiu kombinciju lai piektu pie tlkm vietm."},
{name:"Pieejambas paldzba",legend:"Nospiediet ${a11yHelp}"}]}]});