/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotyczce dostpnoci",contents:"Zawarto pomocy. Wcinij ESC, aby zamkn to okno.",legend:[{name:"Informacje oglne",items:[{name:"Pasek narzdzi edytora",legend:"Wcinij ${toolbarFocus} aby przej do paska narzdzi. Przejd do nastpnej i poprzedniej grupy narzdzi uywajc TAB oraz SHIFT-TAB. Przejd do nastpnego i poprzedniego narzdzia uywajc STRZAKI W PRAWO lub STRZAKI W LEWO. Wcinij SPACJ lub ENTER, aby aktywowa zaznaczone narzdzie."},
{name:"Okno dialogowe edytora",legend:"Bdc w oknie dialogowym wcinij TAB aby przej do nastpnego pola dialogowego, wcinij SHIFT + TAB aby przej do poprzedniego pola, wcinij ENTER aby wysa dialog, wcinij ESC aby anulowa dialog. Dla okien dialogowych z wieloma zakadkami, wcinij ALT + F10 aby przej do listy zakadek. Gdy to zrobisz przejd do nastpnej zakadki wciskajc TAB lub STRZAK W PRAWO. Przejd do poprzedniej zakadki wciskajc SHIFT + TAB lub STRZAK W LEWO. Wcinij SPACJ lub ENTER aby wybra zakadk."},
{name:"Menu kontekstowe edytora",legend:"Wcinij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzy menu kontekstowe. Przejd do nastpnej pozycji menu wciskajc TAB lub STRZAK W D. Przejd do poprzedniej pozycji menu wciskajc SHIFT + TAB lub STRZAK W GR. Wcinij SPACJ lub ENTER aby wygra pozycj menu. Otwrz pod-menu obecnej pozycji wciskajc SPACJ lub ENTER lub STRZAK W PRAWO. Wr do pozycji nadrzdnego menu wciskajc ESC lub STRZAK W LEWO. Zamknij menu wciskajc ESC."},{name:"Lista w edytorze",
legend:"W polu listy moesz przechodzi do nastpnego elementu za pomoc klawisza TAB lub STRZAKI W D. Poprzedni element osigniesz za pomoc SHIFT+TAB lub STRZAKI W GR. Za pomoc SPACJI lub ENTERA wybierzesz dan opcj z listy, a za pomoc klawisza ESC opucisz list."},{name:"Pasek cieki elementw edytora",legend:"Nacinij ${elementsPathFocus} w celu przejcia do paska cieki elementw edytora. W celu przejcia do kolejnego elementu nacinij klawisz Tab lub Strzaki w prawo. W celu przejcia do poprzedniego elementu nacinij klawisze Shift+Tab lub Strzaki w lewo. By wybra element w edytorze, uyj klawisza Spacji lub Enter."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"Nacinij ${undo}"},{name:"Polecenie Ponw",legend:"Nacinij ${redo}"},{name:"Polecenie Pogrubienie",legend:"Nacinij ${bold}"},{name:"Polecenie Kursywa",legend:"Nacinij ${italic}"},{name:"Polecenie Podkrelenie",legend:"Nacinij ${underline}"},{name:"Polecenie Wstaw/ edytuj odnonik",legend:"Nacinij ${link}"},{name:"Polecenie schowaj pasek narzdzi",legend:"Nacinij ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Pomoc dotyczca dostpnoci",legend:"Nacinij ${a11yHelp}"}]}]});