/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"Intrukcie prstupnosti",contents:"Pomocn obsah. Pre zatvorenie tohto okna, stlate ESC.",legend:[{name:"Veobecne",items:[{name:"Lita nstrojov editora",legend:"Stlate ${toolbarFocus} pre navigciu na litu nstrojov. Medzi alou a predchdzajcou litou nstrojov sa pohybujete s TAB a SHIFT-TAB. Medzi alm a predchdzajcim tlaidlom na lite nstrojov sa pohybujete s pravou pkou a avou pkou. Stlate medzernk alebo ENTER pre aktivciu tlaidla lity nstrojov."},
{name:"Editorov dialg",legend:"V dialogu, stlate TAB pre navigciu na alie dialgov pole, stlate STIFT + TAB pre presun na predchdzajce pole, stlate ENTER pre odoslanie dialgu, stlate ESC pre zruenie dialgu. Pre dialgy, ktor maj viac zloiek, stlate ALT + F10 pre navigcou do zoznamu zloiek. Potom sa posvajte k alej loke pomocou TAB alebo pravou pkou. Pre presun k predchdzajcej zloke, stlate SHIFT + TAB alebo av pku. Stlate medzernk alebo ENTER pre vybranie zloky."},
{name:"Editorov kontextov menu",legend:"Stlate ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextovho menu. Potom sa presvajte na alie monosti menu s TAB alebo dolnou pkou. Presunte sa k predchdzajcej monosti s SHIFT + TAB alebo hornou pkou. Stlate medzernk alebo ENTER pre vber monosti menu. Otvorte pod-menu danej monosti s medzernkom, alebo ENTER, alebo pravou pkou. Vrte sa sp do poloky rodiovskho menu s ESC alebo avou pkou. Zatvorte kontextov menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presute sa na aliu poloku v zozname s TAB alebo dolnou pkou. Presute sa k predchdzajcej poloke v zozname so SHIFT + TAB alebo hornou pkou. Stlate medzernk alebo ENTER pre vber monosti zoznamu. Stlate ESC pre zatvorenie boxu zoznamu."},{name:"Editorove psmo cesty prvku",legend:"Stlate ${elementsPathFocus} pre navigovanie na psmo cesty elementu. Presute sa na tlaidlo alieho prvku s TAB alebo pravou pkou. Presute sa k predchdzajcemu tlaidlu s SHIFT + TAB alebo avou pkou. Stlate medzernk alebo ENTER pre vber prvku v editore."}]},
{name:"Prkazy",items:[{name:"Vrti prkazy",legend:"Stlate ${undo}"},{name:"Nanovo vrti prkaz",legend:"Stlate ${redo}"},{name:"Prkaz na stunenie",legend:"Stlate ${bold}"},{name:"Prkaz na kurzvu",legend:"Stlate ${italic}"},{name:"Prkaz na podiarknutie",legend:"Stlate ${underline}"},{name:"Prkaz na odkaz",legend:"Stlate ${link}"},{name:"Prkaz na zbalenie lity nstrojov",legend:"Stlate ${toolbarCollapse}"},{name:"Prejs na predchdzajcu zameraten medzeru prkazu",legend:"Stlate ${accessPreviousSpace} pre prstup na najbliie nedosiahnuten zameraten medzery pred vsuvkuo. Naprklad: dve za sebou idce horizontlne iary. Opakujte kombinciu klvesov pre dosiahnutie vzdialench zameratench medzier."},
{name:"Prejs na al ",legend:"Stlate ${accessNextSpace} pre prstup na najbliie nedosiahnuten zameraten medzery po vsuvke. Naprklad: dve za sebou idce horizontlne iary. Opakujte kombinciu klvesov pre dosiahnutie vzdialench zameratench medzier."},{name:"Pomoc prstupnosti",legend:"Stlate ${a11yHelp}"}]}]});