/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sl",{title:"Navodila Dostopnosti",contents:"Vsebina Pomoi. e elite zapreti to pogovorno okno pritisnite ESC.",legend:[{name:"Splono",items:[{name:"Urejevalna Orodna Vrstica",legend:"Pritisnite ${toolbarFocus} za pomik v orodno vrstico. Z TAB in SHIFT-TAB se pomikate na naslednjo in prejnjo skupino orodne vrstice. Z DESNO PUICO ali LEVO PUICO se pomikate na naslednji in prejnji gumb orodne vrstice. Pritisnite SPACE ali ENTER, da aktivirate gumb orodne vrstice."},
{name:"Urejevalno Pogovorno Okno",legend:"Znotraj pogovornega okna, pritisnite tipko TAB za pomik na naslednjo pogovorno polje, pritisnite SHIFT + TAB za pomik v prejnje polje, pritisnite tipko ENTER za predloitev pogovornega okna, pritisnite tipko ESC, da prekliete okno. Za okna, ki imajo ve zavihkov, pritisnite ALT + F10, da pojdete na seznam zavihkov. Na naslednji zavihek se premaknete s tipko TAB ali DESNO PUICO. Z SHIFT + TAB ali LEVO PUICO pa se premaknete na prejnji zavihek. Pritisnite tipko SPACE ali ENTER za izbiro zavihka."},
{name:"Urejevalni Kontekstni Meni",legend:"Pritisnite ${contextMenu} ali APPLICATION KEY, da odprete kontekstni meni. Nato se premaknite na naslednjo monost menija s tipko TAB ali PUICA DOL. Premakniti se na prejnjo monost z SHIFT + TAB ali PUICA GOR. Pritisnite SPACE ali ENTER za izbiro monosti menija. Odprite podmeni trenutne monosti menija s tipko SPACE ali ENTER ali DESNA PUICA. Vrnite se na matini element menija s tipko ESC ali LEVA PUICA. Zaprite kontekstni meni z ESC."},{name:"Urejevalno Seznamsko Polje",
legend:"Znotraj seznama, se premaknete na naslednji element seznama s tipko TAB ali PUICO DOL. Z SHIFT + TAB ali PUICO GOR se premaknete na prejnji element seznama. Pritisnite tipko SPACE ali ENTER za izbiro elementa. Pritisnite tipko ESC, da zaprete seznam."},{name:"Urejevalna vrstica poti elementa",legend:"Pritisnite ${elementsPathFocus} za pomikanje po vrstici elementnih poti. S TAB ali DESNA PUICA se premaknete na naslednji gumb elementa. Z SHIFT + TAB ali LEVO PUICO se premaknete na prejnji gumb elementa. Pritisnite SPACE ali ENTER za izbiro elementa v urejevalniku."}]},
{name:"Ukazi",items:[{name:"Razveljavi ukaz",legend:"Pritisnite ${undo}"},{name:"Ponovi ukaz",legend:"Pritisnite ${redo}"},{name:"Krepki ukaz",legend:"Pritisnite ${bold}"},{name:"Leei ukaz",legend:"Pritisnite ${italic}"},{name:"Poudarni ukaz",legend:"Pritisnite ${underline}"},{name:"Ukaz povezave",legend:"Pritisnite ${link}"},{name:"Skri Orodno Vrstico Ukaz",legend:"Pritisnite ${toolbarCollapse}"},{name:"Dostop do prejnjega ukaza ostrenja",legend:"Pritisnite ${accessPreviousSpace} za dostop do najblijega nedosegljivega osredotoenega prostora pred streico, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da doseete oddaljene osredotoene prostore."},
{name:"Dostop do naslednjega ukaza ostrenja",legend:"Pritisnite ${accessNextSpace} za dostop do najblijega nedosegljivega osredotoenega prostora po streici, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da doseete oddaljene osredotoene prostore."},{name:"Pomo Dostopnosti",legend:"Pritisnite ${a11yHelp}"}]}]});