/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"Hjlpmedelsinstruktioner",contents:"Hjlpinnehll. Fr att stnga denna dialogruta trycker du p ESC.",legend:[{name:"Allmnt",items:[{name:"Editor verktygsflt",legend:"Tryck p ${toolbarFocus} fr att navigera till verktygsfltet. Flytta till nsta och fregende verktygsfltsgrupp med TAB och SHIFT-TAB. Flytta till nsta och fregende knapp i verktygsfltet med HGERPIL eller VNSTERPIL. Tryck Space eller ENTER fr att aktivera knappen i verktygsfltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB fr att navigera till nsta flt i dialogrutan. Du trycker SKIFT + TAB fr att flytta till fregende flt. Tryck ENTER fr att skicka. Du avbryter och stnger dialogen med ESC. Fr dialogrutor som har flera flikar, tryck ALT + F10 navigera till fliklistan. Flytta sedan till nsta flik med HGERPIL. Flytta till fregende flik med SHIFT + TAB eller VNSTERPIL. Tryck Space eller ENTER fr att vlja fliken."},{name:"Editor fr innehllsmeny",
legend:"Tryck p $ {contextMenu} eller PROGRAMTANGENTEN fr att ppna snabbmenyn. Flytta sedan till nsta menyalternativ med TAB eller NEDPIL. Flytta till fregende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER fr att vlja menyalternativ. ppna undermeny av nuvarande alternativ med SPACE eller ENTER eller HGERPIL. G tillbaka till verordnade menyalternativ med ESC eller VNSTERPIL. Stng snabbmenyn med ESC."},{name:"Editor fr List Box",legend:"Inuti en list-box, g till nsta listobjekt med TAB eller NEDPIL. Flytta till fregende listobjekt med SHIFT + TAB eller UPPIL. Tryck Space eller ENTER fr att vlja listan alternativet. Tryck ESC fr att stnga listan-boxen."},
{name:"Editor fr elementens skvg",legend:"Tryck p $ {elementsPathFocus} fr att navigera till verktygsfltet fr elementens skvgar. Flytta till nsta elementknapp med TAB eller HGERPIL. Flytta till fregende knapp med SKIFT + TAB eller VNSTERPIL. Tryck Space eller ENTER fr att vlja element i redigeraren."}]},{name:"Kommandon",items:[{name:"Kommandot ngra",legend:"Tryck p ${undo}"},{name:"Kommandot gr om",legend:"Tryck p ${redo}"},{name:"Kommandot fet stil",legend:"Tryck p ${bold}"},
{name:"Kommandot kursiv",legend:"Tryck p ${italic}"},{name:"Kommandot understruken",legend:"Tryck p ${underline}"},{name:"kommandot lnk",legend:"Tryck p ${link}"},{name:"Verktygsflt Dlj kommandot",legend:"Tryck p ${toolbarCollapse}"},{name:"G till fregende fokus plats",legend:"Tryck p ${accessPreviousSpace} fr att g till nrmast onbarara utrymme fre markren, exempel: tv intilliggande HR element. Repetera tangentkombinationen fr att g till nsta."},{name:"Tillg nsta fokuskommandots utrymme",
legend:"Tryck ${accessNextSpace} p fr att komma t den nrmaste onbar fokus utrymme efter cirkumflex, till exempel: tv intilliggande HR element. Upprepa tangentkombinationen fr att n avlgsna fokus utrymmen."},{name:"Hjlp om tillgnglighet",legend:"Tryck ${a11yHelp}"}]}]});