/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"Eriilebilirlik Talimatlar",contents:"Yardm ierii. Bu pencereyi kapatmak iin ESC tuuna basn.",legend:[{name:"Genel",items:[{name:"Dzenleyici Ara ubuu",legend:"Ara ubuunda gezinmek iin ${toolbarFocus} basn. TAB ve SHIFT-TAB ile nceki ve sonraki ara ubuu grubuna tayn. SA OK veya SOL OK ile nceki ve sonraki bir ara ubuu dmesini hareket ettirin. SPACE tuuna basn veya ara ubuu dmesini etkinletirmek iin ENTER tuna basn."},
{name:"Diyalog Dzenleyici",legend:"Dialog penceresi iinde, sonraki iletiim alanna gitmek iin SEKME tuuna basn, nceki alana gemek iin SHIFT + TAB tuuna basn, pencereyi gndermek iin ENTER tuuna basn, dialog penceresini iptal etmek iin ESC tuuna basn. Birden ok sekme sayfalar olan diyaloglarn, sekme listesine gitmek iin ALT + F10 tularna basn. Sonra TAB veya SA OK sonraki sekmeye tayn. SHIFT + TAB veya SOL OK ile nceki sekmeye gein. Sekme sayfay semek iin SPACE veya ENTER tuuna basn."},
{name:"erik Men Editr",legend:"erik mensn amak iin ${contextMenu} veya UYGULAMA TUU'na basn. Daha sonra SEKME veya AAI OK ile bir sonraki men seenei tayn. SHIFT + TAB veya YUKARI OK ile nceki seenee gider. Men seeneini semek iin SPACE veya ENTER tuuna basn. Seili seenein alt mensn SPACE ya da ENTER veya SA OK an. st men esini gemek iin ESC veya SOL OK ile geri dnn. ESC ile balam mensn kapatn."},{name:"Liste Kutusu Editr",legend:"Liste kutusu iinde, bir sonraki liste esine SEKME VEYA AAI OK ile tayn. SHIFT + TAB veya YUKARI nceki liste esi tayn. Liste seenei semek iin SPACE veya ENTER tuuna basn. Liste kutusunu kapatmak iin ESC tuuna basn."},
{name:"Element Yol ubuu Editr",legend:"Elementlerin yol ubuunda gezinmek iin ${ElementsPathFocus} basn. SEKME veya SA OK ile sonraki element dmesine tayn. SHIFT + TAB veya SOL OK nceki dmeye hareket ettirin. Editr iindeki elementi semek iin ENTER veya SPACE tuuna basn."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basn"},{name:"Komutu geri al",legend:"${redo} basn"},{name:" Kaln komut",legend:"${bold} basn"},{name:" talik komutu",legend:"${italic} basn"},
{name:" Alttan izgi komutu",legend:"${underline} basn"},{name:" Balant komutu",legend:"${link} basn"},{name:" Ara ubuu Toplama komutu",legend:"${toolbarCollapse} basn"},{name:"nceki komut alanna odaklan",legend:"Dzeltme imleinden nce, en yakn uzaktaki alana erimek iin ${accessPreviousSpace} basn, rnein: iki birleik HR elementleri. Ayn tu kombinasyonu tekraryla dier alanlarada ulan."},{name:"Sonraki komut alanna odaklan",legend:"Dzeltme imleinden sonra, en yakn uzaktaki alana erimek iin ${accessNextSpace} basn, rnein: iki birleik HR elementleri. Ayn tu kombinasyonu tekraryla dier alanlarada ulan."},
{name:"Eriilebilirlik Yardm",legend:"${a11yHelp}'e basn"}]}]});