/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","cs",{euro:"Znak eura",lsquo:"Poten uvozovka jednoduch",rsquo:"Koncov uvozovka jednoduch",ldquo:"Poten uvozovka dvojit",rdquo:"Koncov uvozovka dvojit",ndash:"En pomlka",mdash:"Em pomlka",iexcl:"Obrcen vykink",cent:"Znak centu",pound:"Znak libry",curren:"Znak mny",yen:"Znak jenu",brvbar:"Peruen svisl ra",sect:"Znak oddlu",uml:"Pehlska",copy:"Znak copyrightu",ordf:"ensk indiktor rodu",laquo:"Znak dvojitch lomench uvozovek vlevo",
not:"Logistick zpor",reg:"Znak registrace",macr:"Pomlka nad",deg:"Znak stupn",sup2:"Dvojka jako horn index",sup3:"Trojka jako horn index",acute:"rka nad vpravo",micro:"Znak mikro",para:"Znak odstavce",middot:"Teka uprosted",cedil:"Ocsek vlevo",sup1:"Jednika jako horn index",ordm:"Musk indiktor rodu",raquo:"Znak dvojitch lomench uvozovek vpravo",frac14:"Obyejn zlomek jedna tvrtina",frac12:"Obyejn zlomek jedna polovina",frac34:"Obyejn zlomek ti tvrtiny",iquest:"Znak obrcenho otaznku",
Agrave:"Velk psmeno latinky A s rkou nad vlevo",Aacute:"Velk psmeno latinky A s rkou nad vpravo",Acirc:"Velk psmeno latinky A s voknm",Atilde:"Velk psmeno latinky A s tildou",Auml:"Velk psmeno latinky A s dvma tekami",Aring:"Velk psmeno latinky A s kroukem nad",AElig:"Velk psmeno latinky Ae",Ccedil:"Velk psmeno latinky C s ocskem vlevo",Egrave:"Velk psmeno latinky E s rkou nad vlevo",Eacute:"Velk psmeno latinky E s rkou nad vpravo",Ecirc:"Velk psmeno latinky E s voknm",
Euml:"Velk psmeno latinky E s dvma tekami",Igrave:"Velk psmeno latinky I s rkou nad vlevo",Iacute:"Velk psmeno latinky I s rkou nad vpravo",Icirc:"Velk psmeno latinky I s voknm",Iuml:"Velk psmeno latinky I s dvma tekami",ETH:"Velk psmeno latinky Eth",Ntilde:"Velk psmeno latinky N s tildou",Ograve:"Velk psmeno latinky O s rkou nad vlevo",Oacute:"Velk psmeno latinky O s rkou nad vpravo",Ocirc:"Velk psmeno latinky O s voknm",Otilde:"Velk psmeno latinky O s tildou",
Ouml:"Velk psmeno latinky O s dvma tekami",times:"Znak nsoben",Oslash:"Velk psmeno latinky O pekrtnut",Ugrave:"Velk psmeno latinky U s rkou nad vlevo",Uacute:"Velk psmeno latinky U s rkou nad vpravo",Ucirc:"Velk psmeno latinky U s voknm",Uuml:"Velk psmeno latinky U s dvma tekami",Yacute:"Velk psmeno latinky Y s rkou nad vpravo",THORN:"Velk psmeno latinky Thorn",szlig:"Mal psmeno latinky ostr s",agrave:"Mal psmeno latinky a s rkou nad vlevo",aacute:"Mal psmeno latinky a s rkou nad vpravo",
acirc:"Mal psmeno latinky a s voknm",atilde:"Mal psmeno latinky a s tildou",auml:"Mal psmeno latinky a s dvma tekami",aring:"Mal psmeno latinky a s kroukem nad",aelig:"Mal psmeno latinky ae",ccedil:"Mal psmeno latinky c s ocskem vlevo",egrave:"Mal psmeno latinky e s rkou nad vlevo",eacute:"Mal psmeno latinky e s rkou nad vpravo",ecirc:"Mal psmeno latinky e s voknm",euml:"Mal psmeno latinky e s dvma tekami",igrave:"Mal psmeno latinky i s rkou nad vlevo",iacute:"Mal psmeno latinky i s rkou nad vpravo",
icirc:"Mal psmeno latinky i s voknm",iuml:"Mal psmeno latinky i s dvma tekami",eth:"Mal psmeno latinky eth",ntilde:"Mal psmeno latinky n s tildou",ograve:"Mal psmeno latinky o s rkou nad vlevo",oacute:"Mal psmeno latinky o s rkou nad vpravo",ocirc:"Mal psmeno latinky o s voknm",otilde:"Mal psmeno latinky o s tildou",ouml:"Mal psmeno latinky o s dvma tekami",divide:"Znak dlen",oslash:"Mal psmeno latinky o pekrtnut",ugrave:"Mal psmeno latinky u s rkou nad vlevo",
uacute:"Mal psmeno latinky u s rkou nad vpravo",ucirc:"Mal psmeno latinky u s voknm",uuml:"Mal psmeno latinky u s dvma tekami",yacute:"Mal psmeno latinky y s rkou nad vpravo",thorn:"Mal psmeno latinky thorn",yuml:"Mal psmeno latinky y s dvma tekami",OElig:"Velk ligatura latinky OE",oelig:"Mal ligatura latinky OE",372:"Velk psmeno latinky W s voknm",374:"Velk psmeno latinky Y s voknm",373:"Mal psmeno latinky w s voknm",375:"Mal psmeno latinky y s voknm",sbquo:"Doln 9 uvozovka jednoduch",
8219:"Horn obrcen 9 uvozovka jednoduch",bdquo:"Doln 9 uvozovka dvojit",hellip:"Trojtekov vod",trade:"Obchodn znaka",9658:"ern ukazatel smujc vpravo",bull:"Koleko",rarr:"ipka vpravo",rArr:"Dvojit ipka vpravo",hArr:"Dvojit ipka vlevo a vpravo",diams:"ern piky",asymp:"Tm se rovn"});