/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"Smbolo de euro",lsquo:"Comilla simple izquierda",rsquo:"Comilla simple derecha",ldquo:"Comilla doble izquierda",rdquo:"Comilla doble derecha",ndash:"Guin corto",mdash:"Guin medio largo",iexcl:"Signo de admiracin invertido",cent:"Smbolo centavo",pound:"Smbolo libra",curren:"Smbolo moneda",yen:"Smbolo yen",brvbar:"Barra vertical rota",sect:"Smbolo seccin",uml:"Diresis",copy:"Signo de derechos de autor",ordf:"Indicador ordinal femenino",laquo:"Abre comillas angulares",
not:"Signo negacin",reg:"Signo de marca registrada",macr:"Guin alto",deg:"Signo de grado",sup2:"Superndice dos",sup3:"Superndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"Superndice uno",ordm:"Indicador orginal masculino",raquo:"Cierra comillas angulares",frac14:"Fraccin ordinaria de un quarto",frac12:"Fraccin ordinaria de una mitad",frac34:"Fraccin ordinaria de tres cuartos",iquest:"Signo de interrogacin invertido",Agrave:"Letra A latina mayscula con acento grave",
Aacute:"Letra A latina  mayscula con acento agudo",Acirc:"Letra A latina mayscula con acento circunflejo",Atilde:"Letra A latina mayscula con tilde",Auml:"Letra A latina mayscula con diresis",Aring:"Letra A latina mayscula con aro arriba",AElig:"Letra  latina mayscula",Ccedil:"Letra C latina mayscula con cedilla",Egrave:"Letra E latina mayscula con acento grave",Eacute:"Letra E latina mayscula con acento agudo",Ecirc:"Letra E latina mayscula con acento circunflejo",Euml:"Letra E latina mayscula con diresis",
Igrave:"Letra I latina mayscula con acento grave",Iacute:"Letra I latina mayscula con acento agudo",Icirc:"Letra I latina mayscula con acento circunflejo",Iuml:"Letra I latina mayscula con diresis",ETH:"Letra Eth latina mayscula",Ntilde:"Letra N latina mayscula con tilde",Ograve:"Letra O latina mayscula con acento grave",Oacute:"Letra O latina mayscula con acento agudo",Ocirc:"Letra O latina mayscula con acento circunflejo",Otilde:"Letra O latina mayscula con tilde",Ouml:"Letra O latina mayscula con diresis",
times:"Signo de multiplicacin",Oslash:"Letra O latina mayscula con barra inclinada",Ugrave:"Letra U latina mayscula con acento grave",Uacute:"Letra U latina mayscula con acento agudo",Ucirc:"Letra U latina mayscula con acento circunflejo",Uuml:"Letra U latina mayscula con diresis",Yacute:"Letra Y latina mayscula con acento agudo",THORN:"Letra Thorn latina mayscula",szlig:"Letra s latina fuerte pequea",agrave:"Letra a latina pequea con acento grave",aacute:"Letra a latina pequea con acento agudo",
acirc:"Letra a latina pequea con acento circunflejo",atilde:"Letra a latina pequea con tilde",auml:"Letra a latina pequea con diresis",aring:"Letra a latina pequea con aro arriba",aelig:"Letra  latina pequea",ccedil:"Letra c latina pequea con cedilla",egrave:"Letra e latina pequea con acento grave",eacute:"Letra e latina pequea con acento agudo",ecirc:"Letra e latina pequea con acento circunflejo",euml:"Letra e latina pequea con diresis",igrave:"Letra i latina pequea con acento grave",
iacute:"Letra i latina pequea con acento agudo",icirc:"Letra i latina pequea con acento circunflejo",iuml:"Letra i latina pequea con diresis",eth:"Letra eth latina pequea",ntilde:"Letra n latina pequea con tilde",ograve:"Letra o latina pequea con acento grave",oacute:"Letra o latina pequea con acento agudo",ocirc:"Letra o latina pequea con acento circunflejo",otilde:"Letra o latina pequea con tilde",ouml:"Letra o latina pequea con diresis",divide:"Signo de divisin",oslash:"Letra o latina minscula con barra inclinada",
ugrave:"Letra u latina pequea con acento grave",uacute:"Letra u latina pequea con acento agudo",ucirc:"Letra u latina pequea con acento circunflejo",uuml:"Letra u latina pequea con diresis",yacute:"Letra u latina pequea con acento agudo",thorn:"Letra thorn latina minscula",yuml:"Letra y latina pequea con diresis",OElig:"Diptongo OE latino en mayscula",oelig:"Diptongo oe latino en minscula",372:"Letra W latina mayscula con acento circunflejo",374:"Letra Y latina mayscula con acento circunflejo",
373:"Letra w latina pequea con acento circunflejo",375:"Letra y latina pequea con acento circunflejo",sbquo:"Comilla simple baja-9",8219:"Comilla simple alta invertida-9",bdquo:"Comillas dobles bajas-9",hellip:"Puntos suspensivos horizontales",trade:"Signo de marca registrada",9658:"Apuntador negro apuntando a la derecha",bull:"Vieta",rarr:"Flecha a la derecha",rArr:"Flecha doble a la derecha",hArr:"Flecha izquierda derecha doble",diams:"Diamante negro",asymp:"Casi igual a"});