/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr-ca",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret",iexcl:"Point d'exclamation invers",cent:"Symbole de cent",pound:"Symbole de Livre Sterling",curren:"Symbole montaire",yen:"Symbole du Yen",brvbar:"Barre scinde",sect:"Symbole de section",uml:"Trma",copy:"Symbole de copyright",ordf:"Indicateur ordinal fminin",laquo:"Guillemet franais ouvrant",
not:"Indicateur de ngation",reg:"Symbole de marque dpose",macr:"Macron",deg:"Degr",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aige",micro:"Symbole micro",para:"Paragraphe",middot:"Point mdian",cedil:"Cdille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franais fermant",frac14:"Un quart",frac12:"Une demi",frac34:"Trois quart",iquest:"Point d'interrogation invers",Agrave:"A accent grave",Aacute:"A accent aige",Acirc:"A circonflexe",Atilde:"A tilde",Auml:"A trma",
Aring:"A avec un rond au dessus",AElig:" majuscule",Ccedil:"C cdille",Egrave:"E accent grave",Eacute:"E accent aige",Ecirc:"E accent circonflexe",Euml:"E trma",Igrave:"I accent grave",Iacute:"I accent aige",Icirc:"I accent circonflexe",Iuml:"I trma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N tilde",Ograve:"O accent grave",Oacute:"O accent aige",Ocirc:"O accent circonflexe",Otilde:"O tilde",Ouml:"O trma",times:"Symbole de multiplication",Oslash:"O barr",Ugrave:"U accent grave",Uacute:"U accent aige",
Ucirc:"U accent circonflexe",Uuml:"U trma",Yacute:"Y accent aige",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a accent grave",aacute:"a accent aige",acirc:"a accent circonflexe",atilde:"a tilde",auml:"a trma",aring:"a avec un cercle au dessus",aelig:"",ccedil:"c cdille",egrave:"e accent grave",eacute:"e accent aige",ecirc:"e accent circonflexe",euml:"e trma",igrave:"i accent grave",iacute:"i accent aige",icirc:"i accent circonflexe",iuml:"i trma",
eth:"Lettre minuscule islandaise ED",ntilde:"n tilde",ograve:"o accent grave",oacute:"o accent aige",ocirc:"O accent circonflexe",otilde:"O tilde",ouml:"O trma",divide:"Symbole de division",oslash:"o barr",ugrave:"u accent grave",uacute:"u accent aige",ucirc:"u accent circonflexe",uuml:"u trma",yacute:"y accent aige",thorn:"Lettre islandaise thorn minuscule",yuml:"y trma",OElig:"ligature majuscule latine ",oelig:"ligature minuscule latine ",372:"W accent circonflexe",374:"Y accent circonflexe",
373:"w accent circonflexe",375:"y accent circonflexe",sbquo:"Guillemet simple fermant",8219:"Guillemet-virgule suprieur culbut",bdquo:"Guillemet-virgule double infrieur",hellip:"Points de suspension",trade:"Symbole de marque dpose",9658:"Flche noire pointant vers la droite",bull:"Puce",rarr:"Flche vers la droite",rArr:"Flche double vers la droite",hArr:"Flche double vers la gauche",diams:"Carreau",asymp:"Presque gal"});