/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret cadratin",iexcl:"Point d'exclamation invers",cent:"Symbole Cent",pound:"Symbole Livre Sterling",curren:"Symbole montaire",yen:"Symbole Yen",brvbar:"Barre verticale scinde",sect:"Section",uml:"Trma",copy:"Symbole Copyright",ordf:"Indicateur ordinal fminin",laquo:"Guillemet franais ouvrant",
not:"Crochet de ngation",reg:"Marque dpose",macr:"Macron",deg:"Degr",sup2:"Exposant 2",sup3:"\\tExposant 3",acute:"Accent aigu",micro:"Omicron",para:"Paragraphe",middot:"Point mdian",cedil:"Cdille",sup1:"\\tExposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet franais fermant",frac14:"Un quart",frac12:"Un demi",frac34:"Trois quarts",iquest:"Point d'interrogation invers",Agrave:"A majuscule accent grave",Aacute:"A majuscule accent aigu",Acirc:"A majuscule accent circonflexe",Atilde:"A majuscule avec caron",
Auml:"A majuscule trma",Aring:"A majuscule avec un rond au-dessus",AElig:" majuscule ligaturs",Ccedil:"C majuscule cdille",Egrave:"E majuscule accent grave",Eacute:"E majuscule accent aigu",Ecirc:"E majuscule accent circonflexe",Euml:"E majuscule trma",Igrave:"I majuscule accent grave",Iacute:"I majuscule accent aigu",Icirc:"I majuscule accent circonflexe",Iuml:"I majuscule trma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N majuscule avec caron",Ograve:"O majuscule accent grave",Oacute:"O majuscule accent aigu",
Ocirc:"O majuscule accent circonflexe",Otilde:"O majuscule avec caron",Ouml:"O majuscule trma",times:"Multiplication",Oslash:"O majuscule barr",Ugrave:"U majuscule accent grave",Uacute:"U majuscule accent aigu",Ucirc:"U majuscule accent circonflexe",Uuml:"U majuscule trma",Yacute:"Y majuscule accent aigu",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a minuscule accent grave",aacute:"a minuscule accent aigu",acirc:"a minuscule accent circonflexe",atilde:"a minuscule avec caron",
auml:"a minuscule trma",aring:"a minuscule avec un rond au-dessus",aelig:" minuscule ligaturs",ccedil:"c minuscule cdille",egrave:"e minuscule accent grave",eacute:"e minuscule accent aigu",ecirc:"e minuscule accent circonflexe",euml:"e minuscule trma",igrave:"i minuscule accent grave",iacute:"i minuscule accent aigu",icirc:"i minuscule accent circonflexe",iuml:"i minuscule trma",eth:"Lettre minuscule islandaise ED",ntilde:"n minuscule avec caron",ograve:"o minuscule accent grave",oacute:"o minuscule accent aigu",
ocirc:"o minuscule accent circonflexe",otilde:"o minuscule avec caron",ouml:"o minuscule trma",divide:"Division",oslash:"o minuscule barr",ugrave:"u minuscule accent grave",uacute:"u minuscule accent aigu",ucirc:"u minuscule accent circonflexe",uuml:"u minuscule trma",yacute:"y minuscule accent aigu",thorn:"Lettre islandaise thorn minuscule",yuml:"y minuscule trma",OElig:"ligature majuscule latine ",oelig:"ligature minuscule latine ",372:"W majuscule accent circonflexe",374:"Y majuscule accent circonflexe",
373:"w minuscule accent circonflexe",375:"y minuscule accent circonflexe",sbquo:"Guillemet simple fermant (anglais)",8219:"Guillemet-virgule suprieur culbut",bdquo:"Guillemet-virgule double infrieur",hellip:"Points de suspension",trade:"Marque commerciale (trade mark)",9658:"Flche noire pointant vers la droite",bull:"Gros point mdian",rarr:"Flche vers la droite",rArr:"Double flche vers la droite",hArr:"Double flche vers la gauche",diams:"Carreau noir",asymp:"Presque gal"});