/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","gl",{euro:"Smbolo do euro",lsquo:"Comia simple esquerda",rsquo:"Comia simple dereita",ldquo:"Comias dobres esquerda",rdquo:"Comias dobres dereita",ndash:"Guin",mdash:"Raia",iexcl:"Signo de admiracin invertido",cent:"Smbolo do centavo",pound:"Smbolo da libra",curren:"Smbolo de moeda",yen:"Smbolo do yen",brvbar:"Barra vertical rota",sect:"Smbolo de seccin",uml:"Direse",copy:"Smbolo de dereitos de autora",ordf:"Indicador ordinal feminino",laquo:"Comias latinas, apertura",
not:"Signo negacin",reg:"Smbolo de marca rexistrada",macr:"Guin alto",deg:"Signo de grao",sup2:"Superndice dous",sup3:"Superndice tres",acute:"Acento agudo",micro:"Signo de micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"Superndice un",ordm:"Indicador ordinal masculino",raquo:"Comias latinas, peche",frac14:"Fraccin ordinaria de un cuarto",frac12:"Fraccin ordinaria de un medio",frac34:"Fraccin ordinaria de tres cuartos",iquest:"Signo de interrogacin invertido",Agrave:"Letra A latina maiscula con acento grave",
Aacute:"Letra A latina maiscula con acento agudo",Acirc:"Letra A latina maiscula con acento circunflexo",Atilde:"Letra A latina maiscula con til",Auml:"Letra A latina maiscula con direse",Aring:"Letra A latina maiscula con aro enriba",AElig:"Letra  latina maiscula",Ccedil:"Letra C latina maiscula con cedilla",Egrave:"Letra E latina maiscula con acento grave",Eacute:"Letra E latina maiscula con acento agudo",Ecirc:"Letra E latina maiscula con acento circunflexo",Euml:"Letra E latina maiscula con direse",
Igrave:"Letra I latina maiscula con acento grave",Iacute:"Letra I latina maiscula con acento agudo",Icirc:"Letra I latina maiscula con acento circunflexo",Iuml:"Letra I latina maiscula con direse",ETH:"Letra Ed latina maiscula",Ntilde:"Letra N latina maiscula con til",Ograve:"Letra O latina maiscula con acento grave",Oacute:"Letra O latina maiscula con acento agudo",Ocirc:"Letra O latina maiscula con acento circunflexo",Otilde:"Letra O latina maiscula con til",Ouml:"Letra O latina maiscula con direse",
times:"Signo de multiplicacin",Oslash:"Letra O latina maiscula con barra transversal",Ugrave:"Letra U latina maiscula con acento grave",Uacute:"Letra U latina maiscula con acento agudo",Ucirc:"Letra U latina maiscula con acento circunflexo",Uuml:"Letra U latina maiscula con direse",Yacute:"Letra Y latina maiscula con acento agudo",THORN:"Letra Thorn latina maiscula",szlig:"Letra s latina forte minscula",agrave:"Letra a latina minscula con acento grave",aacute:"Letra a latina minscula con acento agudo",
acirc:"Letra a latina minscula con acento circunflexo",atilde:"Letra a latina minscula con til",auml:"Letra a latina minscula con direse",aring:"Letra a latina minscula con aro enriba",aelig:"Letra  latina minscula",ccedil:"Letra c latina minscula con cedilla",egrave:"Letra e latina minscula con acento grave",eacute:"Letra e latina minscula con acento agudo",ecirc:"Letra e latina minscula con acento circunflexo",euml:"Letra e latina minscula con direse",igrave:"Letra i latina minscula con acento grave",
iacute:"Letra i latina minscula con acento agudo",icirc:"Letra i latina minscula con acento circunflexo",iuml:"Letra i latina minscula con direse",eth:"Letra ed latina minscula",ntilde:"Letra n latina minscula con til",ograve:"Letra o latina minscula con acento grave",oacute:"Letra o latina minscula con acento agudo",ocirc:"Letra o latina minscula con acento circunflexo",otilde:"Letra o latina minscula con til",ouml:"Letra o latina minscula con direse",divide:"Signo de divisin",oslash:"Letra o latina minscula con barra transversal",
ugrave:"Letra u latina minscula con acento grave",uacute:"Letra u latina minscula con acento agudo",ucirc:"Letra u latina minscula con acento circunflexo",uuml:"Letra u latina minscula con direse",yacute:"Letra y latina minscula con acento agudo",thorn:"Letra Thorn latina minscula",yuml:"Letra y latina minscula con direse",OElig:"Ligadura OE latina maiscula",oelig:"Ligadura oe latina minscula",372:"Letra W latina maiscula con acento circunflexo",374:"Letra Y latina maiscula con acento circunflexo",
373:"Letra w latina minscula con acento circunflexo",375:"Letra y latina minscula con acento circunflexo",sbquo:"Comia simple baixa, de apertura",8219:"Comia simple alta, de peche",bdquo:"Comias dobres baixas, de apertura",hellip:"Elipse, puntos suspensivos",trade:"Signo de marca rexistrada",9658:"Apuntador negro apuntando  dereita",bull:"Vieta",rarr:"Frecha  dereita",rArr:"Frecha dobre  dereita",hArr:"Frecha dobre da esquerda  dereita",diams:"Diamante negro",asymp:"Case igual a"});