/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"Eur jel",lsquo:"Bal szimpla idzjel",rsquo:"Jobb szimpla idzjel",ldquo:"Bal dupla idzjel",rdquo:"Jobb dupla idzjel",ndash:"Rvid gondolatjel",mdash:"Hossz gondolatjel",iexcl:"Fordtott felkiltjel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"Hossz kettspont",sect:"Paragrafus jel",uml:"Ketts hangz jel",copy:"Szerzi jog jel",ordf:"Ni sorrend mutatja",laquo:"Balra mutat duplanyl",not:"Feltteles ktjel",
reg:"Bejegyzett vdjegy jele",macr:"Hosszsgi jel",deg:"Fok jel",sup2:"Ngyzeten jel",sup3:"Kbn jel",acute:"les kezet",micro:"Mikro-jel",para:"Bekezds jel",middot:"Kzp pont",cedil:"Cdille",sup1:"Elsn jel",ordm:"Frfi sorrend mutatja",raquo:"Jobbra mutat duplanyl",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"Hrom negyed jel",iquest:"Fordtott krdjel",Agrave:"Latin nagy A fordtott kezettel",Aacute:"Latin nagy A norml kezettel",Acirc:"Latin nagy A hajtott kezettel",Atilde:"Latin nagy A hullmjellel",
Auml:"Latin nagy A kettspont kezettel",Aring:"Latin nagy A gyr kezettel",AElig:"Latin nagy  bet",Ccedil:"Latin nagy C cedillval",Egrave:"Latin nagy E fordtott kezettel",Eacute:"Latin nagy E norml kezettel",Ecirc:"Latin nagy E hajtott kezettel",Euml:"Latin nagy E dupla kettspont kezettel",Igrave:"Latin nagy I fordtott kezettel",Iacute:"Latin nagy I norml kezettel",Icirc:"Latin nagy I hajtott kezettel",Iuml:"Latin nagy I kettspont kezettel",ETH:"Latin nagy Eth bet",Ntilde:"Latin nagy N hullmjellel",
Ograve:"Latin nagy O fordtott kezettel",Oacute:"Latin nagy O norml kezettel",Ocirc:"Latin nagy O hajtott kezettel",Otilde:"Latin nagy O hullmjellel",Ouml:"Latin nagy O kettspont kezettel",times:"Szorzs jel",Oslash:"Latin O bet thzssal",Ugrave:"Latin nagy U fordtott kezettel",Uacute:"Latin nagy U norml kezettel",Ucirc:"Latin nagy U hajtott kezettel",Uuml:"Latin nagy U kettspont kezettel",Yacute:"Latin nagy Y norml kezettel",THORN:"Latin nagy Thorn bet",szlig:"Latin kis s bet",
agrave:"Latin kis a fordtott kezettel",aacute:"Latin kis a norml kezettel",acirc:"Latin kis a hajtott kezettel",atilde:"Latin kis a hullmjellel",auml:"Latin kis a kettspont kezettel",aring:"Latin kis a gyr kezettel",aelig:"Latin kis  bet",ccedil:"Latin kis c cedillval",egrave:"Latin kis e fordtott kezettel",eacute:"Latin kis e norml kezettel",ecirc:"Latin kis e hajtott kezettel",euml:"Latin kis e dupla kettspont kezettel",igrave:"Latin kis i fordtott kezettel",iacute:"Latin kis i norml kezettel",
icirc:"Latin kis i hajtott kezettel",iuml:"Latin kis i kettspont kezettel",eth:"Latin kis eth bet",ntilde:"Latin kis n hullmjellel",ograve:"Latin kis o fordtott kezettel",oacute:"Latin kis o norml kezettel",ocirc:"Latin kis o hajtott kezettel",otilde:"Latin kis o hullmjellel",ouml:"Latin kis o kettspont kezettel",divide:"Osztsjel",oslash:"Latin kis o bet thzssal",ugrave:"Latin kis u fordtott kezettel",uacute:"Latin kis u norml kezettel",ucirc:"Latin kis u hajtott kezettel",
uuml:"Latin kis u kettspont kezettel",yacute:"Latin kis y norml kezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kettspont kezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott kezettel",374:"Latin nagy Y hajtott kezettel",373:"Latin kis w hajtott kezettel",375:"Latin kis y hajtott kezettel",sbquo:"Nyit nyomdai szimpla idzjel",8219:"Zr nyomdai zr idzjel",bdquo:"Nyit nyomdai dupla idzjel",hellip:"Hrom pont",trade:"Kereskedelmi vdjegy jele",
9658:"Jobbra mutat fekete mutat",bull:"Goly",rarr:"Jobbra mutat nyl",rArr:"Jobbra mutat duplanyl",hArr:"Bal-jobb duplanyl",diams:"Fekete gymnt jel",asymp:"Majdnem egyenl jel"});