/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","lv",{euro:"Euro zme",lsquo:"Kreis  vienkrtga pdia",rsquo:"Lab  vienkrtga pdia",ldquo:"Kreis  dubult pdia",rdquo:"Lab dubult pdia",ndash:"En svtra",mdash:"Em svtra",iexcl:"Apgriezta izsaukuma zme",cent:"Centu naudas zme",pound:"Sterliu mrciu naudas zme",curren:"Valtas zme",yen:"Jenu naudas zme",brvbar:"Vertikla prrauta lnija",sect:"Paragrfa zme",uml:"Diakritiska zme",copy:"Autortiesbu zme",ordf:"Sievias krtas rdtjs",
laquo:"Kreis dubult stra pdiu zme",not:"Neparakstts",reg:"Reistrta zme",macr:"Garumzme",deg:"Grdu zme",sup2:"Augraksts divi",sup3:"Augraksts trs",acute:"Akta uzsvara zme",micro:"Mikro zme",para:"Rindkopas zme ",middot:"Vidjs punkts",cedil:"tis zem burta",sup1:"Augraksts viens",ordm:"Vrigas krtas rdtjs",raquo:"Lab dubult stra pdiu zme",frac14:"Vulgra frakcija 1/4",frac12:"Vulgra frakcija 1/2",frac34:"Vulgra frakcija 3/4",iquest:"Apgriezta jautjuma zme",Agrave:"Lielais latu burts A ar uzsvara zmi",
Aacute:"Lielais  latu burts A ar aktu uzsvara zmi",Acirc:"Lielais latu burts A ar diakritisku zmi",Atilde:"Lielais latu burts A ar tildi ",Auml:"Lielais latu burts A ar diakritisko zmi",Aring:"Lielais latu burts A ar aplti aug",AElig:"Lielais latu burts ",Ccedil:"Lielais latu burts C ar ti zem burta",Egrave:"Lielais latu burts E ar apostrofu",Eacute:"Lielais latu burts E ar aktu uzsvara zmi",Ecirc:"Lielais latu burts E ar diakritisko zmi",Euml:"Lielais latu burts E ar diakritisko zmi",
Igrave:"Lielais latu burts I ar uzsvaras  zmi",Iacute:"Lielais latu burts I ar aktu uzsvara zmi",Icirc:"Lielais latu burts I ar diakritisko zmi",Iuml:"Lielais latu burts I ar diakritisko zmi",ETH:"Lielais latu burts Eth",Ntilde:"Lielais latu burts N ar tildi",Ograve:"Lielais latu burts O ar uzsvara zmi",Oacute:"Lielais latu burts O ar akto uzsvara zmi",Ocirc:"Lielais latu burts O ar diakritisko zmi",Otilde:"Lielais latu burts O ar tildi",Ouml:"Lielais latu burts O ar diakritisko zmi",
times:"Reizinanas zme ",Oslash:"Lielais latu burts O ar iesvtrojumu",Ugrave:"Lielais latu burts U ar uzsvaras zmi",Uacute:"Lielais latu burts U ar akto uzsvars zmi",Ucirc:"Lielais latu burts U ar diakritisko zmi",Uuml:"Lielais latu burts U ar diakritisko zmi",Yacute:"Lielais latu burts Y ar akto uzsvaras zmi",THORN:"Lielais latu burts torn",szlig:"Mazs latu burts ar ligatru",agrave:"Mazs latu burts a ar uzsvara zmi",aacute:"Mazs latu burts a ar akto uzsvara zmi",
acirc:"Mazs latu burts a ar diakritisko zmi",atilde:"Mazs latu burts a ar tildi",auml:"Mazs latu burts a ar diakritisko zmi",aring:"Mazs latu burts a ar aplti aug",aelig:"Mazs latu burts ",ccedil:"Mazs latu burts c ar ti zem burta",egrave:"Mazs latu burts e ar uzsvara zmi ",eacute:"Mazs latu burts e ar aktu uzsvara zmi",ecirc:"Mazs latu burts e ar diakritisko zmi",euml:"Mazs latu burts e ar diakritisko zmi",igrave:"Mazs latu burts i ar uzsvara zmi ",iacute:"Mazs latu burts i ar aktu uzsvara zmi",
icirc:"Mazs latu burts i ar diakritisko zmi",iuml:"Mazs latu burts i ar diakritisko zmi",eth:"Mazs latu burts eth",ntilde:"Mazs latu burts n ar tildi",ograve:"Mazs latu burts o ar uzsvara zmi ",oacute:"Mazs latu burts o ar aktu uzsvara zmi",ocirc:"Mazs latu burts o ar diakritisko zmi",otilde:"Mazs latu burts o ar tildi",ouml:"Mazs latu burts o ar diakritisko zmi",divide:"Dalanas zme",oslash:"Mazs latu burts o ar iesvtrojumu",ugrave:"Mazs latu burts u ar uzsvara zmi ",
uacute:"Mazs latu burts u ar  aktu uzsvara zmi",ucirc:"Mazs latu burts u ar diakritisko zmi",uuml:"Mazs latu burts u ar diakritisko zmi",yacute:"Mazs latu burts y ar  aktu uzsvaras zmi",thorn:"Mazs latu burts torns",yuml:"Mazs latu burts y ar diakritisko zmi",OElig:"Liela latu ligatra OE",oelig:"Maza latu ligatra oe",372:"Liels latu burts W ar diakritisko zmi ",374:"Liels latu burts Y ar diakritisko zmi ",373:"Mazs latu burts w ar diakritisko zmi ",375:"Mazs latu burts y ar diakritisko zmi ",
sbquo:"Mazas-9 vienkrtgas pdias",8219:"Lielas-9 vienkrtgas apgrieztas pdias",bdquo:"Mazas-9 dubultas pdias",hellip:"Horizontli daudzpunkti",trade:"Preu zmes zme",9658:"Melns pa labi pagriezts radtjs",bull:"Lode",rarr:"Bulta pa labi",rArr:"Dubulta Bulta pa labi",hArr:"Bulta pa kreisi",diams:"Dubulta Bulta pa kreisi",asymp:"Gandrz viends ar"});