/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"Cudzysw pojedynczy otwierajcy",rsquo:"Cudzysw pojedynczy zamykajcy",ldquo:"Cudzysw apostrofowy otwierajcy",rdquo:"Cudzysw apostrofowy zamykajcy",ndash:"Ppauza",mdash:"Pauza",iexcl:"Odwrcony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"Wskanik rodzaju eskiego liczebnika porzdkowego",
laquo:"Lewy cudzysw ostroktny",not:"Znak negacji",reg:"Zastrzeony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga potga",sup3:"Trzecia potga",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka rodkowa",cedil:"Cedylla",sup1:"Pierwsza potga",ordm:"Wskanik rodzaju mskiego liczebnika porzdkowego",raquo:"Prawy cudzysw ostroktny",frac14:"Uamek zwyky jedna czwarta",frac12:"Uamek zwyky jedna druga",frac34:"Uamek zwyky trzy czwarte",iquest:"Odwrcony znak zapytania",
Agrave:"Wielka litera A z akcentem cikim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przecigym",Atilde:"Wielka litera A z tyld",Auml:"Wielka litera A z dierez",Aring:"Wielka litera A z kkiem",AElig:"Wielka ligatura ",Ccedil:"Wielka litera C z cedyll",Egrave:"Wielka litera E z akcentem cikim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przecigym",Euml:"Wielka litera E z dierez",Igrave:"Wielka litera I z akcentem cikim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przecigym",Iuml:"Wielka litera I z dierez",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tyld",Ograve:"Wielka litera O z akcentem cikim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przecigym",Otilde:"Wielka litera O z tyld",Ouml:"Wielka litera O z dierez",times:"Znak mnoenia wektorowego",Oslash:"Wielka litera O z przekreleniem",Ugrave:"Wielka litera U z akcentem cikim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przecigym",Uuml:"Wielka litera U z dierez",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"Maa litera ostre s (eszet)",agrave:"Maa litera a z akcentem cikim",aacute:"Maa litera a z akcentem ostrym",acirc:"Maa litera a z akcentem przecigym",atilde:"Maa litera a z tyld",auml:"Maa litera a z dierez",aring:"Maa litera a z kkiem",aelig:"Maa ligatura ",ccedil:"Maa litera c z cedyll",egrave:"Maa litera e z akcentem cikim",
eacute:"Maa litera e z akcentem ostrym",ecirc:"Maa litera e z akcentem przecigym",euml:"Maa litera e z dierez",igrave:"Maa litera i z akcentem cikim",iacute:"Maa litera i z akcentem ostrym",icirc:"Maa litera i z akcentem przecigym",iuml:"Maa litera i z dierez",eth:"Maa litera eth",ntilde:"Maa litera n z tyld",ograve:"Maa litera o z akcentem cikim",oacute:"Maa litera o z akcentem ostrym",ocirc:"Maa litera o z akcentem przecigym",otilde:"Maa litera o z tyld",ouml:"Maa litera o z dierez",
divide:"Anglosaski znak dzielenia",oslash:"Maa litera o z przekreleniem",ugrave:"Maa litera u z akcentem cikim",uacute:"Maa litera u z akcentem ostrym",ucirc:"Maa litera u z akcentem przecigym",uuml:"Maa litera u z dierez",yacute:"Maa litera y z akcentem ostrym",thorn:"Maa litera thorn",yuml:"Maa litera y z dierez",OElig:"Wielka ligatura OE",oelig:"Maa ligatura oe",372:"Wielka litera W z akcentem przecigym",374:"Wielka litera Y z akcentem przecigym",373:"Maa litera w z akcentem przecigym",
375:"Maa litera y z akcentem przecigym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof grny",bdquo:"Podwjny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wskanik wskazujcy w prawo",bull:"Punktor",rarr:"Strzaka w prawo",rArr:"Podwjna strzaka w prawo",hArr:"Podwjna strzaka w lewo",diams:"Czarny znak karo",asymp:"Znak prawie rwne"});