/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt-br",{euro:"Euro",lsquo:"Aspas simples esquerda",rsquo:"Aspas simples direita",ldquo:"Aspas duplas esquerda",rdquo:"Aspas duplas direita",ndash:"Trao",mdash:"Travesso",iexcl:"Ponto de exclamao invertido",cent:"Cent",pound:"Cerquilha",curren:"Dinheiro",yen:"Yen",brvbar:"Bara interrompida",sect:"Smbolo de Pargrafo",uml:"Trema",copy:"Direito de Cpia",ordf:"Indicador ordinal feminino",laquo:"Aspas duplas angulares esquerda",not:"Negao",reg:"Marca Registrada",
macr:"Mcron",deg:"Grau",sup2:"2 Superscrito",sup3:"3 Superscrito",acute:"Acento agudo",micro:"Micro",para:"P de mosca",middot:"Ponto mediano",cedil:"Cedilha",sup1:"1 Superscrito",ordm:"Indicador ordinal masculino",raquo:"Aspas duplas angulares direita",frac14:"Um quarto",frac12:"Um meio",frac34:"Trs quartos",iquest:"Interrogao invertida",Agrave:"A maisculo com acento grave",Aacute:"A maisculo com acento agudo",Acirc:"A maisculo com acento circunflexo",Atilde:"A maisculo com til",Auml:"A maisculo com trema",
Aring:"A maisculo com anel acima",AElig:" maisculo",Ccedil:" mailculo",Egrave:"E maisculo com acento grave",Eacute:"E maisculo com acento agudo",Ecirc:"E maisculo com acento circumflexo",Euml:"E maisculo com trema",Igrave:"I maisculo com acento grave",Iacute:"I maisculo com acento agudo",Icirc:"I maisculo com acento circunflexo",Iuml:"I maisculo com crase",ETH:"Eth maisculo",Ntilde:"N maisculo com til",Ograve:"O maisculo com acento grave",Oacute:"O maisculo com acento agudo",Ocirc:"O maisculo com acento circunflexo",
Otilde:"O maisculo com til",Ouml:"O maisculo com trema",times:"Multiplicao",Oslash:"Dimetro",Ugrave:"U maisculo com acento grave",Uacute:"U maisculo com acento agudo",Ucirc:"U maisculo com acento circunflexo",Uuml:"U maisculo com trema",Yacute:"Y maisculo com acento agudo",THORN:"Thorn maisculo",szlig:"Eszett minsculo",agrave:"a minsculo com acento grave",aacute:"a minsculo com acento agudo",acirc:"a minsculo com acento circunflexo",atilde:"a minsculo com til",auml:"a minsculo com trema",
aring:"a minsculo com anel acima",aelig:" minsculo",ccedil:" minsculo",egrave:"e minsculo com acento grave",eacute:"e minsculo com acento agudo",ecirc:"e minsculo com acento circunflexo",euml:"e minsculo com trema",igrave:"i minsculo com acento grave",iacute:"i minsculo com acento agudo",icirc:"i minsculo com acento circunflexo",iuml:"i minsculo com trema",eth:"eth minsculo",ntilde:"n minsculo com til",ograve:"o minsculo com acento grave",oacute:"o minsculo com acento agudo",ocirc:"o minsculo com acento circunflexo",
otilde:"o minsculo com til",ouml:"o minsculo com trema",divide:"Diviso",oslash:"o minsculo com cortado ou dimetro",ugrave:"u minsculo com acento grave",uacute:"u minsculo com acento agudo",ucirc:"u minsculo com acento circunflexo",uuml:"u minsculo com trema",yacute:"y minsculo com acento agudo",thorn:"thorn minsculo",yuml:"y minsculo com trema",OElig:"Ligao tipogrfica OE maiscula",oelig:"Ligao tipogrfica oe minscula",372:"W maisculo com acento circunflexo",374:"Y maisculo com acento circunflexo",
373:"w minsculo com acento circunflexo",375:"y minsculo com acento circunflexo",sbquo:"Aspas simples inferior direita",8219:"Aspas simples superior esquerda",bdquo:"Aspas duplas inferior direita",hellip:"Reticncias",trade:"Trade mark",9658:"Ponta de seta preta para direita",bull:"Ponto lista",rarr:"Seta para direita",rArr:"Seta dupla para direita",hArr:"Seta dupla direita e esquerda",diams:"Ouros",asymp:"Aproximadamente"});