/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.html or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt",{euro:"Smbolo do Euro",lsquo:"Aspas simples pra Esquerda",rsquo:"Aspas simples pra Direita",ldquo:"Aspas duplas pra Esquerda",rdquo:"Aspas duplas pra Direita",ndash:"Travesso Simples",mdash:"Travesso Longo",iexcl:"Ponto de exclamao invertido",cent:"Smbolo do Cntimo",pound:"Smbolo da Libra",curren:"Smbolo da Moeda",yen:"Smbolo do Iene",brvbar:"Barra quebrada",sect:"Smbolo de Seco",uml:"Trema",copy:"Smbolo dos Direitos de Autor",ordf:"Indicador ordinal feminino",
laquo:"Aspas ngulo duplo pra Esquerda",not:"No Smbolo",reg:"Smbolo de Registado",macr:"Mcron",deg:"Smbolo de Grau",sup2:"Expoente 2",sup3:"Expoente 3",acute:"Acento Agudo",micro:"Smbolo de Micro",para:"Smbolo de Pargrafo",middot:"Ponto do Meio",cedil:"Cedilha",sup1:"Expoente 1",ordm:"Indicador ordinal masculino",raquo:"Aspas ngulo duplo pra Direita",frac14:"Frao vulgar 1/4",frac12:"Frao vulgar 1/2",frac34:"Frao vulgar 3/4",iquest:"Ponto de interrugao invertido",Agrave:"Letra maiscula latina A com acento grave",
Aacute:"Letra maiscula latina A com acento agudo",Acirc:"Letra maiscula latina A com circunflexo",Atilde:"Letra maiscula latina A com til",Auml:"Letra maiscula latina A com trema",Aring:"Letra maiscula latina A com sinal diacrtico",AElig:"Letra Maiscula Latina ",Ccedil:"Letra maiscula latina C com cedilha",Egrave:"Letra maiscula latina E com acento grave",Eacute:"Letra maiscula latina E com acento agudo",Ecirc:"Letra maiscula latina E com circunflexo",Euml:"Letra maiscula latina E com trema",
Igrave:"Letra maiscula latina I com acento grave",Iacute:"Letra maiscula latina I com acento agudo",Icirc:"Letra maiscula latina I com cincunflexo",Iuml:"Letra maiscula latina I com trema",ETH:"Letra maiscula latina Eth ()",Ntilde:"Letra maiscula latina N com til",Ograve:"Letra maiscula latina O com acento grave",Oacute:"Letra maiscula latina O com acento agudo",Ocirc:"Letra maiscula latina I com circunflexo",Otilde:"Letra maiscula latina O com til",Ouml:"Letra maiscula latina O com trema",
times:"Smbolo de Multiplicao",Oslash:"Letra maiscula O com barra",Ugrave:"Letra maiscula latina U com acento grave",Uacute:"Letra maiscula latina U com acento agudo",Ucirc:"Letra maiscula latina U com circunflexo",Uuml:"Letra maiscula latina E com trema",Yacute:"Letra maiscula latina Y com acento agudo",THORN:"Letra maiscula latina Rnico",szlig:"Letra minscula latina s forte",agrave:"Letra minscula latina a com acento grave",aacute:"Letra minscula latina a com acento agudo",acirc:"Letra minscula latina a com circunflexo",
atilde:"Letra minscula latina a com til",auml:"Letra minscula latina a com trema",aring:"Letra minscula latina a com sinal diacrtico",aelig:"Letra minscula latina ",ccedil:"Letra minscula latina c com cedilha",egrave:"Letra minscula latina e com acento grave",eacute:"Letra minscula latina e com acento agudo",ecirc:"Letra minscula latina e com circunflexo",euml:"Letra minscula latina e com trema",igrave:"Letra minscula latina i com acento grave",iacute:"Letra minscula latina i com acento agudo",
icirc:"Letra minscula latina i com circunflexo",iuml:"Letra pequena latina i com trema",eth:"Letra minscula latina eth",ntilde:"Letra minscula latina n com til",ograve:"Letra minscula latina o com acento grave",oacute:"Letra minscula latina o com acento agudo",ocirc:"Letra minscula latina o com circunflexo",otilde:"Letra minscula latina o com til",ouml:"Letra minscula latina o com trema",divide:"Smbolo de Diviso",oslash:"Letra minscula latina o com barra",ugrave:"Letra minscula latina u com acento grave",
uacute:"Letra minscula latina u com acento agudo",ucirc:"Letra minscula latina u com circunflexo",uuml:"Letra minscula latina u com trema",yacute:"Letra minscula latina y com acento agudo",thorn:"Letra minscula latina Rnico",yuml:"Letra minscula latina y com trema",OElig:"Ligadura maiscula latina OE",oelig:"Ligadura minscula latina oe",372:"Letra maiscula latina W com circunflexo",374:"Letra maiscula latina Y com circunflexo",373:"Letra minscula latina w com circunflexo",375:"Letra minscula latina y com circunflexo",
sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Elipse Horizontal ",trade:"Smbolo de Marca Registada",9658:"Black right-pointing pointer",bull:"Marca",rarr:"Rightwards arrow",rArr:"Rightwards double arrow",hArr:"Left right double arrow",diams:"Black diamond suit",asymp:"Quase igual a "});