/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sk",{euro:"Znak eura",lsquo:"av jednoduch vodzovka",rsquo:"Prav jednoduch vodzovka",ldquo:"Prav dvojit vodzovka",rdquo:"Prav dvojit vodzovka",ndash:"En pomlka",mdash:"Em pomlka",iexcl:"Obrten vkrink",cent:"Znak centu",pound:"Znak libry",curren:"Znak meny",yen:"Znak jenu",brvbar:"Preruen zvisl iara",sect:"Znak odseku",uml:"Prehlska",copy:"Znak copyrightu",ordf:"ensk indiktor rodu",laquo:"Znak dvojitch lomench vodzoviek vavo",not:"Logistick zpor",
reg:"Znak registrcie",macr:"Pomlka nad",deg:"Znak stupa",sup2:"Dvojka ako horn index",sup3:"Trojka ako horn index",acute:"De",micro:"Znak mikro",para:"Znak odstavca",middot:"Bodka uprostred",cedil:"Chvost vavo",sup1:"Jednotka ako horn index",ordm:"Musk indiktor rodu",raquo:"Znak dvojitch lomench vodzoviek vpravo",frac14:"Obyajn zlomok jedna tvrtina",frac12:"Obyajn zlomok jedna polovica",frac34:"Obyajn zlomok tri tvrtiny",iquest:"Otoen otznik",Agrave:"Vek psmeno latinky A s accentom",
Aacute:"Vek psmeno latinky A s dom",Acirc:"Vek psmeno latinky A s mkeom",Atilde:"Vek psmeno latinky A s tildou",Auml:"Vek psmeno latinky A s dvoma bodkami",Aring:"Vek psmeno latinky A s krkom nad",AElig:"Vek psmeno latinky ",Ccedil:"Vek psmeno latinky C s chvostom vavo",Egrave:"Vek psmeno latinky E s accentom",Eacute:"Vek psmeno latinky E s dom",Ecirc:"Vek psmeno latinky E s mkeom",Euml:"Vek psmeno latinky E s dvoma bodkami",Igrave:"Vek psmeno latinky I s accentom",
Iacute:"Vek psmeno latinky I s dom",Icirc:"Vek psmeno latinky I s mkeom",Iuml:"Vek psmeno latinky I s dvoma bodkami",ETH:"Vek psmeno latinky Eth",Ntilde:"Vek psmeno latinky N s tildou",Ograve:"Vek psmeno latinky O s accentom",Oacute:"Vek psmeno latinky O s dom",Ocirc:"Vek psmeno latinky O s mkeom",Otilde:"Vek psmeno latinky O s tildou",Ouml:"Vek psmeno latinky O s dvoma bodkami",times:"Znak nsobenia",Oslash:"Vek psmeno latinky O prekrtnut",Ugrave:"Vek psmeno latinky U s accentom",
Uacute:"Vek psmeno latinky U s dom",Ucirc:"Vek psmeno latinky U s mkeom",Uuml:"Vek psmeno latinky U s dvoma bodkami",Yacute:"Vek psmeno latinky Y s dom",THORN:"Vek psmeno latinky Thorn",szlig:"Mal psmeno latinky ostr s",agrave:"Mal psmeno latinky a s accentom",aacute:"Mal psmeno latinky a s dom",acirc:"Mal psmeno latinky a s mkeom",atilde:"Mal psmeno latinky a s tildou",auml:"Mal psmeno latinky a s dvoma bodkami",aring:"Mal psmeno latinky a s krkom nad",
aelig:"Mal psmeno latinky ",ccedil:"Mal psmeno latinky c s chvostom vavo",egrave:"Mal psmeno latinky e s accentom",eacute:"Mal psmeno latinky e s dom",ecirc:"Mal psmeno latinky e s mkeom",euml:"Mal psmeno latinky e s dvoma bodkami",igrave:"Mal psmeno latinky i s accentom",iacute:"Mal psmeno latinky i s dom",icirc:"Mal psmeno latinky i s mkeom",iuml:"Mal psmeno latinky i s dvoma bodkami",eth:"Mal psmeno latinky eth",ntilde:"Mal psmeno latinky n s tildou",ograve:"Mal psmeno latinky o s accentom",
oacute:"Mal psmeno latinky o s dom",ocirc:"Mal psmeno latinky o s mkeom",otilde:"Mal psmeno latinky o s tildou",ouml:"Mal psmeno latinky o s dvoma bodkami",divide:"Znak delenia",oslash:"Mal psmeno latinky o prekrtnut",ugrave:"Mal psmeno latinky u s accentom",uacute:"Mal psmeno latinky u s dom",ucirc:"Mal psmeno latinky u s mkeom",uuml:"Mal psmeno latinky u s dvoma bodkami",yacute:"Mal psmeno latinky y s dom",thorn:"Mal psmeno latinky thorn",yuml:"Mal psmeno latinky y s dvoma bodkami",
OElig:"Vek ligatra latinky OE",oelig:"Mal ligatra latinky OE",372:"Vek psmeno latinky W s mkeom",374:"Vek psmeno latinky Y s mkeom",373:"Mal psmeno latinky w s mkeom",375:"Mal psmeno latinky y s mkeom",sbquo:"Doln jednoduch 9-vodzovka",8219:"Horn jednoduch otoen 9-vodzovka",bdquo:"Doln dvojit 9-vodzovka",hellip:"Trojbodkov vod",trade:"Znak ibchodnej znaky",9658:"ierny ukazovate smerujci vpravo",bull:"Kruh",rarr:"pka vpravo",rArr:"Dvojit ipka vpravo",
hArr:"Dvojit ipka vavo a vpravo",diams:"ierne piky",asymp:"Skoro sa rovn"});