/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"Thonjza majtas me nj vi",rsquo:"Thonjza djathtas me nj vi",ldquo:"Thonjza majtas",rdquo:"Thonjza djathtas",ndash:"En viza lidhse",mdash:"Em viza lidhse",iexcl:"Pikuditse e prmbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valuts",yen:"Shenja e Jenit",brvbar:"Viza e kputur",sect:"Shenja e pjess",uml:"Diaeresis",copy:"Shenja e t drejtave t kopjimit",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Nuk ka shenj",reg:"Registered sign",macr:"Macron",deg:"Shenja e shkalls",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mpreht",micro:"Shjenja e Mikros",para:"Pilcrow sign",middot:"Pika e Mesme",cedil:"Hark nn shkronja",sup1:"Super-skripta nj",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Thyesa nj t katrat",frac12:"Thyesa nj t dytat",frac34:"Thyesa tre t katrat",iquest:"Pikpyetje e prmbysur",Agrave:"Shkronja e madhe latine A me theks t rnd",
Aacute:"Shkronja e madhe latine A me theks akute",Acirc:"Shkronja e madhe latine A me theks lakor",Atilde:"Shkronja e madhe latine A me tild",Auml:"Shkronja e madhe latine A me dy pika",Aring:"Shkronja e madhe latine A me unaz mbi",AElig:"Shkronja e madhe latine ",Ccedil:"Shkronja e madhe latine C me hark posht",Egrave:"Shkronja e madhe latine E me theks t rnd",Eacute:"Shkronja e madhe latine E me theks akute",Ecirc:"Shkronja e madhe latine E me theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
Igrave:"Shkronja e madhe latine I me theks t rnd",Iacute:"Shkronja e madhe latine I me theks akute",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronja e madhe latine I me dy pika",ETH:"Shkronja e madhe latine Eth",Ntilde:"Shkronja e madhe latine N me tild",Ograve:"Shkronja e madhe latine O me theks t rnd",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tild",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shumzimit",Oslash:"Shkronja e madhe latine O me viz n mes",Ugrave:"Shkronja e madhe latine U me theks t rnd",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e vog latine s e mpreht",agrave:"Shkronja e vog latine a me theks t rnd",aacute:"Shkronja e vog latine a me theks t mpreht",
acirc:"Shkronja e vogl latine a me theks lakor",atilde:"Shkronja e vogl latine a me tild",auml:"Shkronja e vogl latine a me dy pika",aring:"Shkronja e vog latine a me unaz mbi",aelig:"Shkronja e vog latine ",ccedil:"Shkronja e vogl latine c me hark posht",egrave:"Shkronja e vog latine e me theks t rnd",eacute:"Shkronja e vog latine e me theks t mpreht",ecirc:"Shkronja e vogl latine e me theks lakor",euml:"Shkronja e vogl latine e me dy pika",igrave:"Shkronja e vog latine i me theks t rnd",
iacute:"Shkronja e vog latine i me theks t mpreht",icirc:"Shkronja e vogl latine i me theks lakor",iuml:"Shkronja e vogl latine i me dy pika",eth:"Shkronja e vog latine eth",ntilde:"Shkronja e vogl latine n me tild",ograve:"Shkronja e vog latine o me theks t rnd",oacute:"Shkronja e vog latine o me theks t mpreht",ocirc:"Shkronja e vogl latine o me theks lakor",otilde:"Shkronja e vogl latine o me tild",ouml:"Shkronja e vogl latine o me dy pika",divide:"Shenja ndarse",oslash:"Shkronja e vogl latine o me viz n mes",
ugrave:"Shkronja e vog latine u me theks t rnd",uacute:"Shkronja e vog latine u me theks t mpreht",ucirc:"Shkronja e vogl latine u me theks lakor",uuml:"Shkronja e vogl latine u me dy pika",yacute:"Shkronja e vog latine y me theks t mpreht",thorn:"Shkronja e vogl latine thorn",yuml:"Shkronja e vogl latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vogl e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vogl latine w me theks lakor",375:"Shkronja e vogl latine y me theks lakor",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Shenja e Simbolit Tregtar",9658:"Black right-pointing pointer",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Rightwards double arrow",hArr:"Shigjeta e dyfish majtas-djathtas",diams:"Black diamond suit",asymp:"Gati e barabar me"});