/*
 Copyright (c) 2003-2013, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","tr",{euro:"Euro iareti",lsquo:"Sol tek trnak iareti",rsquo:"Sa tek trnak iareti",ldquo:"Sol ift trnak iareti",rdquo:"Sa ift trnak iareti",ndash:"En tire",mdash:"Em tire",iexcl:"Ters nlem iareti",cent:"Cent iareti",pound:"Pound iareti",curren:"Para birimi iareti",yen:"Yen iareti",brvbar:"Krk bar",sect:"Blm iareti",uml:"ki sesli harfin ayrlmas",copy:"Telif hakk iareti",ordf:"Diil sral gsterge",laquo:"Sol-iaret ift a trnak iareti",
not:"Not iareti",reg:"Kaytl iareti",macr:"Makron",deg:"Derece iareti",sup2:"kili stsimge",sup3:"l stsimge",acute:"Aksan iareti",micro:"Mikro iareti",para:"Pilcrow iareti",middot:"Orta nokta",cedil:"Kedilla",sup1:"stsimge",ordm:"Eril sral gsterge",raquo:"Sa iaret ift a trnak iareti",frac14:"Baya kesrin drtte biri",frac12:"Baya kesrin bir yarm",frac34:"Baya kesrin drtte ",iquest:"Ters soru iareti",Agrave:"Aksanl latin harfi",Aacute:"Ar aksanyla Latin harfi",
Acirc:"arpk Latin harfi",Atilde:"Tilde latin harfi",Auml:"Sesli harf ayrlml latin harfi",Aring:"Halkal latin byk A harfi",AElig:"Latin byk  harfi",Ccedil:"Latin byk C harfi ile kedilla",Egrave:"Aksanl latin byk E harfi",Eacute:"Ar vurgulu latin byk E harfi",Ecirc:"arpk latin byk E harfi",Euml:"Sesli harf ayrlml latin byk E harfi",Igrave:"Aksanl latin byk I harfi",Iacute:"Ar aksanl latin byk I harfi",Icirc:"arpk latin byk I harfi",Iuml:"Sesli harf ayrlml latin byk I harfi",
ETH:"Latin byk Eth harfi",Ntilde:"Tildeli latin byk N harfi",Ograve:"Aksanl latin byk O harfi",Oacute:"Ar aksanl latin byk O harfi",Ocirc:"arpk latin byk O harfi",Otilde:"Tildeli latin byk O harfi",Ouml:"Sesli harf ayrlml latin byk O harfi",times:"arpma iareti",Oslash:"Vurgulu latin byk O harfi",Ugrave:"Aksanl latin byk U harfi",Uacute:"Ar aksanl latin byk U harfi",Ucirc:"arpk latin byk U harfi",Uuml:"Sesli harf ayrlml latin byk U harfi",Yacute:"Ar aksanl latin byk Y harfi",
THORN:"Latin byk Thorn harfi",szlig:"Latin kk keskin s harfi",agrave:"Aksanl latin kk a harfi",aacute:"Ar aksanl latin kk a harfi",acirc:"arpk latin kk a harfi",atilde:"Tildeli latin kk a harfi",auml:"Sesli harf ayrlml latin kk a harfi",aring:"Halkal latin kk a harfi",aelig:"Latin byk  harfi",ccedil:"Kedillal latin kk c harfi",egrave:"Aksanl latin kk e harfi",eacute:"Ar aksanl latin kk e harfi",ecirc:"arpk latin kk e harfi",euml:"Sesli harf ayrlml latin kk e harfi",
igrave:"Aksanl latin kk i harfi",iacute:"Ar aksanl latin kk i harfi",icirc:"arpk latin kk i harfi",iuml:"Sesli harf ayrlml latin kk i harfi",eth:"Latin kk eth harfi",ntilde:"Tildeli latin kk n harfi",ograve:"Aksanl latin kk o harfi",oacute:"Ar aksanl latin kk o harfi",ocirc:"arpk latin kk o harfi",otilde:"Tildeli latin kk o harfi",ouml:"Sesli harf ayrlml latin kk o harfi",divide:"Blme iareti",oslash:"Vurgulu latin kk o harfi",ugrave:"Aksanl latin kk u harfi",
uacute:"Ar aksanl latin kk u harfi",ucirc:"arpk latin kk u harfi",uuml:"Sesli harf ayrlml latin kk u harfi",yacute:"Ar aksanl latin kk y harfi",thorn:"Latin kk thorn harfi",yuml:"Sesli harf ayrlml latin kk y harfi",OElig:"Latin byk bal OE harfi",oelig:"Latin kk bal oe harfi",372:"arpk latin byk W harfi",374:"arpk latin byk Y harfi",373:"arpk latin kk w harfi",375:"arpk latin kk y harfi",sbquo:"Tek dk-9 trnak iareti",8219:"Tek yksek-ters-9 trnak iareti",
bdquo:"ift dk-9 trnak iareti",hellip:"Yatay elips",trade:"Marka tescili iareti",9658:"Siyah sa iaret iaretisi",bull:"Koyu nokta",rarr:"Saa doru ok",rArr:"Saa doru ift ok",hArr:"Sol, sa ift ok",diams:"Siyah elmas takm",asymp:"Hemen hemen eit"});