<?
class CountriesDescrs{
	public static $Data=array(
		 		'AU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/22px-Flag_of_Australia.svg.png',
			'name'=>'Австралия'
		),
		'AT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/22px-Flag_of_Austria.svg.png',
			'name'=>'Австрия'
		),
		'AZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/22px-Flag_of_Azerbaijan.svg.png',
			'name'=>'Азербайджан'
		),
		'AX'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_%C3%85land.svg/22px-Flag_of_%C3%85land.svg.png',
			'name'=>'Аландские острова'
		),
		'AL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/22px-Flag_of_Albania.svg.png',
			'name'=>'Албания'
		),
		'DZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/22px-Flag_of_Algeria.svg.png',
			'name'=>'Алжир'
		),
		'VI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/22px-Flag_of_the_United_States_Virgin_Islands.svg.png',
			'name'=>'Виргинские Острова (США)'
		),
		'AS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/22px-Flag_of_American_Samoa.svg.png',
			'name'=>'Американское Самоа'
		),
		'AI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/22px-Flag_of_Anguilla.svg.png',
			'name'=>'Ангилья'
		),
		'AO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/22px-Flag_of_Angola.svg.png',
			'name'=>'Ангола'
		),
		'AD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/22px-Flag_of_Andorra.svg.png',
			'name'=>'Андорра'
		),
		'AQ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Antarctica.svg/22px-Flag_of_Antarctica.svg.png',
			'name'=>'Антарктида'
		),
		'AG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/22px-Flag_of_Antigua_and_Barbuda.svg.png',
			'name'=>'Антигуа и Барбуда'
		),
		'AR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/22px-Flag_of_Argentina.svg.png',
			'name'=>'Аргентина'
		),
		'AM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/22px-Flag_of_Armenia.svg.png',
			'name'=>'Армения'
		),
		'AW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/22px-Flag_of_Aruba.svg.png',
			'name'=>'Аруба'
		),
		'AF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/22px-Flag_of_Afghanistan.svg.png',
			'name'=>'Афганистан'
		),
		'BS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/22px-Flag_of_the_Bahamas.svg.png',
			'name'=>'Багамы'
		),
		'BD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/22px-Flag_of_Bangladesh.svg.png',
			'name'=>'Бангладеш'
		),
		'BB'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/22px-Flag_of_Barbados.svg.png',
			'name'=>'Барбадос'
		),
		'BH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/22px-Flag_of_Bahrain.svg.png',
			'name'=>'Бахрейн'
		),
		'BZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/22px-Flag_of_Belize.svg.png',
			'name'=>'Белиз'
		),
		'BY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/22px-Flag_of_Belarus.svg.png',
			'name'=>'Белоруссия'
		),
		'BE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/22px-Flag_of_Belgium_%28civil%29.svg.png',
			'name'=>'Бельгия'
		),
		'BJ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/22px-Flag_of_Benin.svg.png',
			'name'=>'Бенин'
		),
		'BM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/22px-Flag_of_Bermuda.svg.png',
			'name'=>'Бермуды'
		),
		'BG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/22px-Flag_of_Bulgaria.svg.png',
			'name'=>'Болгария'
		),
		'BO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Bolivia_%28state%29.svg/22px-Flag_of_Bolivia_%28state%29.svg.png',
			'name'=>'Боливия'
		),
		'BQ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/22px-Flag_of_the_Netherlands.svg.png',
			'name'=>'Бонэйр, Синт-Эстатиус и Саба'
		),
		'BA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/22px-Flag_of_Bosnia_and_Herzegovina.svg.png',
			'name'=>'Босния и Герцеговина'
		),
		'BW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/22px-Flag_of_Botswana.svg.png',
			'name'=>'Ботсвана'
		),
		'BR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png',
			'name'=>'Бразилия'
		),
		'IO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_the_British_Indian_Ocean_Territory.svg/22px-Flag_of_the_British_Indian_Ocean_Territory.svg.png',
			'name'=>'Британская территория в Индийском океане'
		),
		'VG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/22px-Flag_of_the_British_Virgin_Islands.svg.png',
			'name'=>'Британские Виргинские острова'
		),
		'BN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/22px-Flag_of_Brunei.svg.png',
			'name'=>'Бруней'
		),
		'BF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/22px-Flag_of_Burkina_Faso.svg.png',
			'name'=>'Буркина-Фасо'
		),
		'BI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/22px-Flag_of_Burundi.svg.png',
			'name'=>'Бурунди'
		),
		'BT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/22px-Flag_of_Bhutan.svg.png',
			'name'=>'Бутан'
		),
		'VU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/22px-Flag_of_Vanuatu.svg.png',
			'name'=>'Вануату'
		),
		'VA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/20px-Flag_of_the_Vatican_City.svg.png',
			'name'=>'Ватикан'
		),
		'GB'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/22px-Flag_of_the_United_Kingdom.svg.png',
			'name'=>'Великобритания'
		),
		'HU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/22px-Flag_of_Hungary.svg.png',
			'name'=>'Венгрия'
		),
		'VE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/22px-Flag_of_Venezuela_%28state%29.svg.png',
			'name'=>'Венесуэла'
		),
		'UM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png',
			'name'=>'Внешние малые острова (США)'
		),
		'TL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/22px-Flag_of_East_Timor.svg.png',
			'name'=>'Восточный Тимор'
		),
		'VN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/22px-Flag_of_Vietnam.svg.png',
			'name'=>'Вьетнам'
		),
		'GA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/22px-Flag_of_Gabon.svg.png',
			'name'=>'Габон'
		),
		'HT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/22px-Flag_of_Haiti.svg.png',
			'name'=>'Гаити'
		),
		'GY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/22px-Flag_of_Guyana.svg.png',
			'name'=>'Гайана'
		),
		'GM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/22px-Flag_of_The_Gambia.svg.png',
			'name'=>'Гамбия'
		),
		'GH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/22px-Flag_of_Ghana.svg.png',
			'name'=>'Гана'
		),
		'GP'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Guadeloupe_%28local%29.svg/22px-Flag_of_Guadeloupe_%28local%29.svg.png',
			'name'=>'Гваделупа'
		),
		'GT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/22px-Flag_of_Guatemala.svg.png',
			'name'=>'Гватемала'
		),
		'GF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_French_Guiana.svg/22px-Flag_of_French_Guiana.svg.png',
			'name'=>'Гвиана'
		),
		'GN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/22px-Flag_of_Guinea.svg.png',
			'name'=>'Гвинея'
		),
		'GW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/22px-Flag_of_Guinea-Bissau.svg.png',
			'name'=>'Гвинея-Бисау'
		),
		'DE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/22px-Flag_of_Germany.svg.png',
			'name'=>'Германия'
		),
		'GG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/22px-Flag_of_Guernsey.svg.png',
			'name'=>'Гернси'
		),
		'GI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/22px-Flag_of_Gibraltar.svg.png',
			'name'=>'Гибралтар'
		),
		'HN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/22px-Flag_of_Honduras.svg.png',
			'name'=>'Гондурас'
		),
		'HK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/22px-Flag_of_Hong_Kong.svg.png',
			'name'=>'Гонконг'
		),
		'GD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/22px-Flag_of_Grenada.svg.png',
			'name'=>'Гренада'
		),
		'GL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/22px-Flag_of_Greenland.svg.png',
			'name'=>'Гренландия'
		),
		'GR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/22px-Flag_of_Greece.svg.png',
			'name'=>'Греция'
		),
		'GE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/22px-Flag_of_Georgia.svg.png',
			'name'=>'Грузия'
		),
		'GU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/22px-Flag_of_Guam.svg.png',
			'name'=>'Гуам'
		),
		'DK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/22px-Flag_of_Denmark.svg.png',
			'name'=>'Дания'
		),
		'JE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/22px-Flag_of_Jersey.svg.png',
			'name'=>'Джерси'
		),
		'DJ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/22px-Flag_of_Djibouti.svg.png',
			'name'=>'Джибути'
		),
		'DM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/22px-Flag_of_Dominica.svg.png',
			'name'=>'Доминика'
		),
		'DO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/22px-Flag_of_the_Dominican_Republic.svg.png',
			'name'=>'Доминиканская Республика'
		),
		'CD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/22px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png',
			'name'=>'Демократическая Республика Конго'
		),
		'EU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Flag_of_Europe.svg/22px-Flag_of_Europe.svg.png',
			'name'=>'undefined'
		),
		'EG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/22px-Flag_of_Egypt.svg.png',
			'name'=>'Египет'
		),
		'ZM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/22px-Flag_of_Zambia.svg.png',
			'name'=>'Замбия'
		),
		'EH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/22px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png',
			'name'=>'САДР'
		),
		'ZW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/22px-Flag_of_Zimbabwe.svg.png',
			'name'=>'Зимбабве'
		),
		'IL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/22px-Flag_of_Israel.svg.png',
			'name'=>'Израиль'
		),
		'IN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/22px-Flag_of_India.svg.png',
			'name'=>''
		),
		'ID'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/22px-Flag_of_Indonesia.svg.png',
			'name'=>'Индонезия'
		),
		'JO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/22px-Flag_of_Jordan.svg.png',
			'name'=>'Иордания'
		),
		'IQ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/22px-Flag_of_Iraq.svg.png',
			'name'=>'Ирак'
		),
		'IR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/22px-Flag_of_Iran.svg.png',
			'name'=>'Иран'
		),
		'IE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/22px-Flag_of_Ireland.svg.png',
			'name'=>'undefined'
		),
		'IS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/22px-Flag_of_Iceland.svg.png',
			'name'=>'Исландия'
		),
		'ES'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/22px-Flag_of_Spain.svg.png',
			'name'=>'Испания'
		),
		'IT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/22px-Flag_of_Italy.svg.png',
			'name'=>'Италия'
		),
		'YE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/22px-Flag_of_Yemen.svg.png',
			'name'=>'Йемен'
		),
		'CV'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/22px-Flag_of_Cape_Verde.svg.png',
			'name'=>'Кабо-Верде'
		),
		'KZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/22px-Flag_of_Kazakhstan.svg.png',
			'name'=>'Казахстан'
		),
		'KY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/22px-Flag_of_the_Cayman_Islands.svg.png',
			'name'=>'Острова Кайман'
		),
		'KH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/22px-Flag_of_Cambodia.svg.png',
			'name'=>'Камбоджа'
		),
		'CM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/22px-Flag_of_Cameroon.svg.png',
			'name'=>'Камерун'
		),
		'CA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/22px-Flag_of_Canada.svg.png',
			'name'=>'Канада'
		),
		'QA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/22px-Flag_of_Qatar.svg.png',
			'name'=>'Катар'
		),
		'KE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/22px-Flag_of_Kenya.svg.png',
			'name'=>'Кения'
		),
		'CY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/22px-Flag_of_Cyprus.svg.png',
			'name'=>'Кипр'
		),
		'KG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/22px-Flag_of_Kyrgyzstan.svg.png',
			'name'=>'Киргизия'
		),
		'KI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/22px-Flag_of_Kiribati.svg.png',
			'name'=>'Кирибати'
		),
		'TW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/22px-Flag_of_the_Republic_of_China.svg.png',
			'name'=>'Китайская Республика'
		),
		'KP'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/22px-Flag_of_North_Korea.svg.png',
			'name'=>'КНДР'
		),
		'CN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/22px-Flag_of_the_People%27s_Republic_of_China.svg.png',
			'name'=>'КНР'
		),
		'CC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg/22px-Flag_of_the_Cocos_%28Keeling%29_Islands.svg.png',
			'name'=>'Кокосовые острова'
		),
		'CO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/22px-Flag_of_Colombia.svg.png',
			'name'=>'Колумбия'
		),
		'KM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/22px-Flag_of_the_Comoros.svg.png',
			'name'=>'Коморы'
		),
		'CR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/22px-Flag_of_Costa_Rica_%28state%29.svg.png',
			'name'=>'Коста-Рика'
		),
		'CI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/22px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png',
			'name'=>'Кот-д’Ивуар'
		),
		'CU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/22px-Flag_of_Cuba.svg.png',
			'name'=>'Куба'
		),
		'KW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/22px-Flag_of_Kuwait.svg.png',
			'name'=>'Кувейт'
		),
		'CW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/22px-Flag_of_Cura%C3%A7ao.svg.png',
			'name'=>'Кюрасао'
		),
		'LA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/22px-Flag_of_Laos.svg.png',
			'name'=>'Лаос'
		),
		'LV'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/22px-Flag_of_Latvia.svg.png',
			'name'=>'Латвия'
		),
		'LS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/22px-Flag_of_Lesotho.svg.png',
			'name'=>'Лесото'
		),
		'LR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/22px-Flag_of_Liberia.svg.png',
			'name'=>'Либерия'
		),
		'LB'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/22px-Flag_of_Lebanon.svg.png',
			'name'=>'Ливан'
		),
		'LY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/22px-Flag_of_Libya.svg.png',
			'name'=>'Ливия'
		),
		'LT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/22px-Flag_of_Lithuania.svg.png',
			'name'=>'Литва'
		),
		'LI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/22px-Flag_of_Liechtenstein.svg.png',
			'name'=>'Лихтенштейн'
		),
		'LU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/22px-Flag_of_Luxembourg.svg.png',
			'name'=>'Люксембург'
		),
		'MU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/22px-Flag_of_Mauritius.svg.png',
			'name'=>'Маврикий'
		),
		'MR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/22px-Flag_of_Mauritania.svg.png',
			'name'=>'Мавритания'
		),
		'MG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/22px-Flag_of_Madagascar.svg.png',
			'name'=>'Мадагаскар'
		),
		'YT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Mayotte_%28local%29.svg/22px-Flag_of_Mayotte_%28local%29.svg.png',
			'name'=>'Майотта'
		),
		'MO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/22px-Flag_of_Macau.svg.png',
			'name'=>'Макао'
		),
		'MK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Macedonia.svg/22px-Flag_of_Macedonia.svg.png',
			'name'=>'Македония'
		),
		'MW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/22px-Flag_of_Malawi.svg.png',
			'name'=>'Малави'
		),
		'MY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/22px-Flag_of_Malaysia.svg.png',
			'name'=>'Малайзия'
		),
		'ML'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/22px-Flag_of_Mali.svg.png',
			'name'=>'Мали'
		),
		'MV'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/22px-Flag_of_Maldives.svg.png',
			'name'=>'Мальдивы'
		),
		'MT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/22px-Flag_of_Malta.svg.png',
			'name'=>'Мальта'
		),
		'MA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/22px-Flag_of_Morocco.svg.png',
			'name'=>'Марокко'
		),
		'MQ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_Martinique.svg/22px-Flag_of_Martinique.svg.png',
			'name'=>'Мартиника'
		),
		'MH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/22px-Flag_of_the_Marshall_Islands.svg.png',
			'name'=>'Маршалловы Острова'
		),
		'MX'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/22px-Flag_of_Mexico.svg.png',
			'name'=>'Мексика'
		),
		'FM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/22px-Flag_of_the_Federated_States_of_Micronesia.svg.png',
			'name'=>'Микронезия'
		),
		'MZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/22px-Flag_of_Mozambique.svg.png',
			'name'=>'Мозамбик'
		),
		'MD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/22px-Flag_of_Moldova.svg.png',
			'name'=>'Молдавия'
		),
		'MC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/22px-Flag_of_Monaco.svg.png',
			'name'=>'Монако'
		),
		'MN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/22px-Flag_of_Mongolia.svg.png',
			'name'=>'Монголия'
		),
		'MS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/22px-Flag_of_Montserrat.svg.png',
			'name'=>'Монтсеррат'
		),
		'MM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/22px-Flag_of_Myanmar.svg.png',
			'name'=>'Мьянма'
		),
		'NA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/22px-Flag_of_Namibia.svg.png',
			'name'=>'Намибия'
		),
		'NR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/22px-Flag_of_Nauru.svg.png',
			'name'=>'Науру'
		),
		'NP'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/16px-Flag_of_Nepal.svg.png',
			'name'=>'Непал'
		),
		'NE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/22px-Flag_of_Niger.svg.png',
			'name'=>'Нигер'
		),
		'NG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/22px-Flag_of_Nigeria.svg.png',
			'name'=>'Нигерия'
		),
		'NL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/22px-Flag_of_the_Netherlands.svg.png',
			'name'=>'Нидерланды'
		),
		'NI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/22px-Flag_of_Nicaragua.svg.png',
			'name'=>'Никарагуа'
		),
		'NU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/22px-Flag_of_Niue.svg.png',
			'name'=>'Ниуэ'
		),
		'NZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/22px-Flag_of_New_Zealand.svg.png',
			'name'=>'Новая Зеландия'
		),
		'NC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Flag_of_New_Caledonia.svg/22px-Flag_of_New_Caledonia.svg.png',
			'name'=>'Новая Каледония'
		),
		'NO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/22px-Flag_of_Norway.svg.png',
			'name'=>'Норвегия'
		),
		'AE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/22px-Flag_of_the_United_Arab_Emirates.svg.png',
			'name'=>'ОАЭ'
		),
		'OM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/22px-Flag_of_Oman.svg.png',
			'name'=>'Оман'
		),
		'BV'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/22px-Flag_of_Norway.svg.png',
			'name'=>'Остров Буве'
		),
		'IM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Flag_of_the_Isle_of_Mann.svg/22px-Flag_of_the_Isle_of_Mann.svg.png',
			'name'=>'Остров Мэн'
		),
		'CK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/22px-Flag_of_the_Cook_Islands.svg.png',
			'name'=>'Острова Кука'
		),
		'NF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/22px-Flag_of_Norfolk_Island.svg.png',
			'name'=>'Остров Норфолк'
		),
		'CX'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/22px-Flag_of_Christmas_Island.svg.png',
			'name'=>'Остров Рождества'
		),
		'PN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/22px-Flag_of_the_Pitcairn_Islands.svg.png',
			'name'=>'Острова Питкэрн'
		),
		'SH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/22px-Flag_of_Saint_Helena.svg.png',
			'name'=>'Острова Святой Елены, Вознесения и Тристан-да-Кунья'
		),
		'PK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/22px-Flag_of_Pakistan.svg.png',
			'name'=>'Пакистан'
		),
		'PW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/22px-Flag_of_Palau.svg.png',
			'name'=>'Палау'
		),
		'PS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/22px-Flag_of_Palestine.svg.png',
			'name'=>'Государство Палестина'
		),
		'PA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/22px-Flag_of_Panama.svg.png',
			'name'=>'Панама'
		),
		'PG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/22px-Flag_of_Papua_New_Guinea.svg.png',
			'name'=>'Папуа — Новая Гвинея'
		),
		'PY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/22px-Flag_of_Paraguay.svg.png',
			'name'=>'Парагвай'
		),
		'PE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Peru_%28state%29.svg/22px-Flag_of_Peru_%28state%29.svg.png',
			'name'=>'Перу'
		),
		'PL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/22px-Flag_of_Poland.svg.png',
			'name'=>'Польша'
		),
		'PT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/22px-Flag_of_Portugal.svg.png',
			'name'=>'Португалия'
		),
		'PR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/22px-Flag_of_Puerto_Rico.svg.png',
			'name'=>'Пуэрто-Рико'
		),
		'CG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/22px-Flag_of_the_Republic_of_the_Congo.svg.png',
			'name'=>'Республика Конго'
		),
		'KR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/22px-Flag_of_South_Korea.svg.png',
			'name'=>'Республика Корея'
		),
		'RE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/ru/thumb/8/84/Regional_Flag_of_Reunion.gif/22px-Regional_Flag_of_Reunion.gif',
			'name'=>'Реюньон'
		),
		'RU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/22px-Flag_of_Russia.svg.png',
			'name'=>'Россия'
		),
		'RW'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/22px-Flag_of_Rwanda.svg.png',
			'name'=>'Руанда'
		),
		'RO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/22px-Flag_of_Romania.svg.png',
			'name'=>'Румыния'
		),
		'SV'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/22px-Flag_of_El_Salvador.svg.png',
			'name'=>'Сальвадор'
		),
		'WS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/22px-Flag_of_Samoa.svg.png',
			'name'=>'Самоа'
		),
		'SM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/22px-Flag_of_San_Marino.svg.png',
			'name'=>'Сан-Марино'
		),
		'ST'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/22px-Flag_of_Sao_Tome_and_Principe.svg.png',
			'name'=>'Сан-Томе и Принсипи'
		),
		'SA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/22px-Flag_of_Saudi_Arabia.svg.png',
			'name'=>'Саудовская Аравия'
		),
		'SZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Swaziland.svg/22px-Flag_of_Swaziland.svg.png',
			'name'=>'Свазиленд'
		),
		'MP'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/22px-Flag_of_the_Northern_Mariana_Islands.svg.png',
			'name'=>'Северные Марианские острова'
		),
		'SC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/22px-Flag_of_Seychelles.svg.png',
			'name'=>'Сейшельские Острова'
		),
		'BL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Saint_Barthelemy_%28local%29.svg/22px-Flag_of_Saint_Barthelemy_%28local%29.svg.png',
			'name'=>'Сен-Бартелеми'
		),
		'MF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Saint-Martin_%28fictional%29.svg/22px-Flag_of_Saint-Martin_%28fictional%29.svg.png',
			'name'=>'Сен-Мартен'
		),
		'PM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg/22px-Flag_of_Saint-Pierre_and_Miquelon.svg.png',
			'name'=>'Сен-Пьер и Микелон'
		),
		'SN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/22px-Flag_of_Senegal.svg.png',
			'name'=>'Сенегал'
		),
		'VC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/22px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png',
			'name'=>'Сент-Винсент и Гренадины'
		),
		'KN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/22px-Flag_of_Saint_Kitts_and_Nevis.svg.png',
			'name'=>'Сент-Китс и Невис'
		),
		'LC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/22px-Flag_of_Saint_Lucia.svg.png',
			'name'=>'Сент-Люсия'
		),
		'RS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/22px-Flag_of_Serbia.svg.png',
			'name'=>'Сербия'
		),
		'SG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/22px-Flag_of_Singapore.svg.png',
			'name'=>'Сингапур'
		),
		'SX'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Sint_Maarten.svg/22px-Flag_of_Sint_Maarten.svg.png',
			'name'=>'Синт-Мартен'
		),
		'SY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/22px-Flag_of_Syria.svg.png',
			'name'=>'Сирия'
		),
		'SK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/22px-Flag_of_Slovakia.svg.png',
			'name'=>'Словакия'
		),
		'SI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/22px-Flag_of_Slovenia.svg.png',
			'name'=>'Словения'
		),
		'SB'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/22px-Flag_of_the_Solomon_Islands.svg.png',
			'name'=>'Соломоновы Острова'
		),
		'SO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/22px-Flag_of_Somalia.svg.png',
			'name'=>'Сомали'
		),
		'SD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/22px-Flag_of_Sudan.svg.png',
			'name'=>'Судан'
		),
		'SU'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_the_Soviet_Union.svg/22px-Flag_of_the_Soviet_Union.svg.png',
			'name'=>'СССР'
		),
		'SR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/22px-Flag_of_Suriname.svg.png',
			'name'=>'Суринам'
		),
		'US'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/22px-Flag_of_the_United_States.svg.png',
			'name'=>'США'
		),
		'SL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/22px-Flag_of_Sierra_Leone.svg.png',
			'name'=>'Сьерра-Леоне'
		),
		'TJ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/22px-Flag_of_Tajikistan.svg.png',
			'name'=>'Таджикистан'
		),
		'TH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/22px-Flag_of_Thailand.svg.png',
			'name'=>'Таиланд'
		),
		'TZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/22px-Flag_of_Tanzania.svg.png',
			'name'=>'Танзания'
		),
		'TC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/22px-Flag_of_the_Turks_and_Caicos_Islands.svg.png',
			'name'=>'Тёркс и Кайкос'
		),
		'TG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/22px-Flag_of_Togo.svg.png',
			'name'=>'Того'
		),
		'TK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/22px-Flag_of_Tokelau.svg.png',
			'name'=>'Токелау'
		),
		'TO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/22px-Flag_of_Tonga.svg.png',
			'name'=>'Тонга'
		),
		'TT'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/22px-Flag_of_Trinidad_and_Tobago.svg.png',
			'name'=>'Тринидад и Тобаго'
		),
		'TV'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/22px-Flag_of_Tuvalu.svg.png',
			'name'=>'Тувалу'
		),
		'TN'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/22px-Flag_of_Tunisia.svg.png',
			'name'=>'Тунис'
		),
		'TM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/22px-Flag_of_Turkmenistan.svg.png',
			'name'=>'Туркмения'
		),
		'TR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/22px-Flag_of_Turkey.svg.png',
			'name'=>'Турция'
		),
		'UG'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/22px-Flag_of_Uganda.svg.png',
			'name'=>'Уганда'
		),
		'UZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/22px-Flag_of_Uzbekistan.svg.png',
			'name'=>'Узбекистан'
		),
		'UA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/22px-Flag_of_Ukraine.svg.png',
			'name'=>'Украина'
		),
		'WF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/22px-Flag_of_France.svg.png',
			'name'=>'Уоллис и Футуна'
		),
		'UY'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/22px-Flag_of_Uruguay.svg.png',
			'name'=>'Уругвай'
		),
		'FO'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/22px-Flag_of_the_Faroe_Islands.svg.png',
			'name'=>'Фареры'
		),
		'FJ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/22px-Flag_of_Fiji.svg.png',
			'name'=>'Фиджи'
		),
		'PH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/22px-Flag_of_the_Philippines.svg.png',
			'name'=>'Филиппины'
		),
		'FI'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/22px-Flag_of_Finland.svg.png',
			'name'=>'Финляндия'
		),
		'FK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/22px-Flag_of_the_Falkland_Islands.svg.png',
			'name'=>'Фолклендские острова'
		),
		'FR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/22px-Flag_of_France.svg.png',
			'name'=>'Франция'
		),
		'PF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/22px-Flag_of_French_Polynesia.svg.png',
			'name'=>'Французская Полинезия'
		),
		'TF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/22px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png',
			'name'=>'Французские Южные и Антарктические Территории'
		),
		'HM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/22px-Flag_of_Australia.svg.png',
			'name'=>'Херд и Макдональд'
		),
		'HR'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/22px-Flag_of_Croatia.svg.png',
			'name'=>'Хорватия'
		),
		'CF'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/22px-Flag_of_the_Central_African_Republic.svg.png',
			'name'=>'ЦАР'
		),
		'TD'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/22px-Flag_of_Chad.svg.png',
			'name'=>'Чад'
		),
		'ME'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/22px-Flag_of_Montenegro.svg.png',
			'name'=>'Черногория'
		),
		'CZ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/22px-Flag_of_the_Czech_Republic.svg.png',
			'name'=>'Чехия'
		),
		'CL'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/22px-Flag_of_Chile.svg.png',
			'name'=>'Чили'
		),
		'CH'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/20px-Flag_of_Switzerland.svg.png',
			'name'=>'Швейцария'
		),
		'SE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/22px-Flag_of_Sweden.svg.png',
			'name'=>'Швеция'
		),
		'SJ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/22px-Flag_of_Norway.svg.png',
			'name'=>'undefined'
		),
		'LK'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/22px-Flag_of_Sri_Lanka.svg.png',
			'name'=>'Шри-Ланка'
		),
		'EC'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/22px-Flag_of_Ecuador.svg.png',
			'name'=>'Эквадор'
		),
		'GQ'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/22px-Flag_of_Equatorial_Guinea.svg.png',
			'name'=>'Экваториальная Гвинея'
		),
		'ER'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/22px-Flag_of_Eritrea.svg.png',
			'name'=>'Эритрея'
		),
		'EE'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/22px-Flag_of_Estonia.svg.png',
			'name'=>'Эстония'
		),
		'ET'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/22px-Flag_of_Ethiopia.svg.png',
			'name'=>'Эфиопия'
		),
		'ZA'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/22px-Flag_of_South_Africa.svg.png',
			'name'=>'ЮАР'
		),
		'GS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg/22px-Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg.png',
			'name'=>'Южная Георгия и Южные Сандвичевы острова'
		),
		'SS'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/22px-Flag_of_South_Sudan.svg.png',
			'name'=>'Южный Судан'
		),
		'JM'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/22px-Flag_of_Jamaica.svg.png',
			'name'=>'Ямайка'
		),
		'JP'=>array(
			'flag'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/22px-Flag_of_Japan.svg.png',
			'name'=>'Япония'
		)

	
	);
	
	 
}

?>